Update Visitor.ts
swc-project/swc pull request #1394
Opened 2021-02-13 03:00 UTC by jaeh

#### Bug:
Adding a custom visitor breaks swc builds.

#### Solution:
`Visitor.visitObjectPattern` was changing n.props, 
`Visitor.visitObjectExpression` uses n.properties.

changed `Visitor.visitObjectPattern` to use n.properties too.

Example that breaks the build:
```
import V from '@swc/core/Visitor.js'
const Visitor = V.default

export default class LinkWrapper extends Visitor {
  // this makes the build work without changing swc core.
  visitObjectPattern(n) {
    n.properties = this.visitObjectPatternProperties(n.properties);
    n.typeAnnotation = this.visitTsTypeAnnotation(n.typeAnnotation);
    return n;
  }

  // without visitObjectPattern above, swc breaks in Visitor.visitObjectPatternProperties
  visitCallExpression(e) {
    if (e.callee.type !== 'MemberExpression') {
      return e
    }

    console.log('memberexpression', e.callee.object.type, e.callee.object.value)

    return e
  }
}

```
 usage in js:
```
const swcOptions = {
  /// ...
  plugin: m => new LinkWrapper().visitModule(m),
}
```

thanks for this tool, took my dev build from ~1.5 seconds to 200ms.
off to (re)create my custom babel Visitor tasks for swc now :)

2021-02-13 03:19 UTC, jaeh commented
will update and add the type signature.

2021-02-14 10:58 UTC, kdy1 requested changes

2021-02-14 10:58 UTC, kdy1 commented on node-swc/src/Visitor.ts
> +      n.props = this.visitObjectProperties(n.props);
This is wrong.
See https://github.com/swc-project/swc/blob/f5a90ae985c3a5dff80fb8f83facc5196093d4d7/ecmascript/ast/src/expr.rs#L184

2021-02-14 10:58 UTC, kdy1 commented on node-swc/src/types.ts
> +  props: (Property | SpreadElement)[];
Same as above/

2021-02-17 03:46 UTC, kdy1 commented
Closing as it's wrong

2021-02-17 03:46 UTC, closed without merging