Support tsconfig paths in spack.
swc-project/swc pull request #2054
Opened 2021-08-11 06:10 UTC by tmpfs

So that setting paths in `options.jsc.paths` in `spack.config.js` is respected when resolving modules.

2021-08-11 06:17 UTC, tmpfs commented
@kdy1, I though this would solve my problem with aliasing builtin modules but it doesn't work so I think `spack` needs to introduce the concept of *aliases*.

For example, I have a dependency that requires the node builtin module `stream` but I am building for the browser so I want to use `stream-browserify` instead. Currently, paths do not allow me to do that as I get this error:

```
not processed by tsc resolver because base module is in node_modules
```

Can we add an `alias` configuration to `spack.config.js` that would just do a straight rewriting of a module `source` on a match:

```json
alias: {
  stream: "stream-browserify",
  fs: "localstorage-fs"
}
```

I think we could add this to `NodeModulesResolver`, would that work?

2021-08-11 08:07 UTC, kdy1 approved these changes
Seems like a good change. Thanks!

2021-08-12 02:01 UTC, tmpfs commented
@kdy1, I have added the `alias` functionality which is helping me a lot step through my build errors. One small detail I changed is that I figured it would be better to allow different aliases per target runtime environment for isomorphic builds, so the config now looks like:

```javascript
alias: {
  browser: {
    stream: "stream-browserify"
  }
}
```

The downside is that if somebody wants the same aliases for `node` and the `browser` some duplication is required but I think it is better to allow them to be configured individually.

I think this can be merged now if you approve :+1:

2021-08-12 03:44 UTC, kdy1 requested changes
Mostly looks good. Thanks!
I have some small changes to propose.

2021-08-12 03:44 UTC, kdy1 commented on spack/src/config/mod.rs
> +    pub alias: HashMap<TargetEnv, HashMap<String, String>>,
Can you use `fxhash::HashMap` instead?

2021-08-12 03:44 UTC, kdy1 commented on src/lib.rs
> +        alias: HashMap<String, String>,
Same here.

2021-08-12 03:44 UTC, kdy1 commented on src/lib.rs
> +        alias: HashMap<String, String>,
Same here.

2021-08-12 05:05 UTC, tmpfs commented
Cool @kdy1, all done :+1:

2021-08-12 05:19 UTC, kdy1 approved these changes
LGTM. Thank you!

2021-08-12 05:30 UTC, merged