fix: Make crate features with global effects optional.
swc-project/swc pull request #2270
Opened 2021-09-18 14:27 UTC by losfair

The `swc` crate currently has two features that cause issues when used as a library:

- `log/release_max_level_info`. This feature silences `debug` and `trace` logs globally in *all* crates that depend on the `log` crate.
- `swc_node_base` which depends on the `mimalloc-rust` crate and sets a custom allocator. Users of the `swc` crate may want to provide their own allocator, and the global allocator feature requires a nightly compiler.

This pull request makes these two features optional, while leaving them enabled by default to preserve the current behavior.

2021-09-18 14:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/swc-project/swc?pullRequest=2270) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/swc-project/swc?pullRequest=2270) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/swc-project/swc?pullRequest=2270) it.</sub>

2021-09-18 14:35 UTC, kdy1 requested changes

2021-09-18 14:35 UTC, kdy1 commented on Cargo.toml
> +default = ["es3", "filter-logs", "custom-allocator"]
Please remove these features completely and move them to `node/binding`.

2021-09-18 14:35 UTC, kdy1 commented on Cargo.toml
> +custom-allocator = ["swc_node_base"]
This should be removed.

2021-09-18 14:35 UTC, kdy1 commented on Cargo.toml
> +swc_node_base = {version = "0.3.0", path = "./node/base", optional = true}
Please move this to `dev-dependencies`. It's required to get correct profiling result.

2021-09-18 14:35 UTC, kdy1 commented on Cargo.toml
> +swc_node_base = {version = "0.3.0", path = "./node/base", optional = true}
Also, please make it not optional.

2021-09-18 14:36 UTC, kdy1 commented
I'm curious about the usecase. Can you share it?
Initially, I didn't expect any user to depend on `swc` crate.

2021-09-18 17:34 UTC, losfair commented
I'm using `swc` to compile TypeScript files to JavaScript as part of the build process in [rusty-workers](https://github.com/losfair/rusty-workers) v2 (the specific branch is WIP and isn't public yet). The usage looks like:

```rust
let compiler = Compiler::new(Arc::new(SourceMap::default()));
// ... prepare source, handlers and opts
let out = compiler.process_js_file(source, &handler, &opts).unwrap();
```

Is there any better ways to do that? It looks like the parser and codegen are there but needs some glueing to put it together so I just depended on `swc` directly.

2021-09-19 07:26 UTC, kdy1 approved these changes
LGTM. Thanks!

2021-09-19 08:05 UTC, merged