Feat added nesting selector
swc-project/swc pull request #2641
Opened 2021-11-03 13:56 UTC by alexander-akait

Added `NestingSelector` as separate node, if we need to support:
```
.foo {
  color: blue;
  & > .bar { color: red; }
}
```

i.e. nested nesting selector, we should keep them in `SubclassSelector` (same for TypeSelector (NamespacedName)), and validate it is first or not (I will fix it in future)

Also we fix here span for `*` selector

2021-11-04 11:52 UTC, kdy1 commented
Is this in specificaiton?

2021-11-04 11:55 UTC, alexander-akait commented
@kdy1 Here https://www.w3.org/TR/css-nesting-1/, it is draft, but if we need support `&` we should follow to this spec (node `&` is supported by css-in-js) and it should be separated AST node

2021-11-06 16:18 UTC, alexander-akait commented
@kdy1 Can you review this too?

2021-11-06 16:29 UTC, kdy1 requested changes
Thanks!
I found one tiny issue.

2021-11-06 16:29 UTC, kdy1 commented on css/codegen/src/lib.rs
> +        let ctx = Ctx { ..self.ctx };
Seems like a redundant code.

2021-11-06 16:32 UTC, alexander-akait commented on css/codegen/src/lib.rs
> +        let ctx = Ctx { ..self.ctx };
Hm, yep, fixed

2021-11-06 16:50 UTC, kdy1 approved these changes
Thanks!
I think rustc is smart enough to remove useless calls...

2021-11-06 16:51 UTC, alexander-akait commented
> Thanks!
> I think rustc is smart enough to remove useless calls...

Yep, I found some more places with this, remove them in other PRs

2021-11-06 16:58 UTC, merged

2021-11-09 21:47 UTC, vpontis commented
@alexander-akait / @kdy1, thank you for the great work!

Does SWC support nested CSS? I tried to use nested CSS w/ the newest version of Next.js and I got this:

<img width="763" alt="CleanShot 2021-11-09 at 16 44 48@2x" src="https://user-images.githubusercontent.com/1319079/141009923-d73c497e-6d5a-4432-8114-6e34a8900de3.png">

Example repo: https://github.com/vpontis/swc-nested-css

---

For more context, we want to switch lu.ma's Next.js project from babel to swc but we use [`@styled-jsx/plugin-scss`](https://yarnpkg.com/package/@styled-jsx/plugin-sass) to give us support for nested CSS selectors. 

We would be able to get rid of SCSS if we can use native nesting in CSS. (Or we could use SWC if you have support for SCSS in styled-jsx, but I'm guessing that will be difficult...)

2021-11-09 21:49 UTC, alexander-akait commented
@vpontis Will support (some limitations right now), but not ready yet, anyway it should parse, can't you provide full CSS?

2021-11-09 21:52 UTC, vpontis commented
Cool thanks, @alexander-akait!

So it's going to be a pretty big migration for us to get rid of SCSS. And it'll be even bigger if we also need to remove nested classes. 

Also we really like using nested CSS for development, so we are trying to preserve that functionality for DX.