Refactor pseudo class and pseudo element
swc-project/swc pull request #2675
Opened 2021-11-07 18:08 UTC by alexander-akait

Added `PseudoClassSelector` amd `PseudoElementSelector`.

Based on grammar https://www.w3.org/TR/selectors-4/#grammar:

- pseudo element and pseudo classes is different types so let's us different AST nodes
- separating them in the future will allow for more efficient tranformations, for example 

> The four Level 2 pseudo-elements (::before, ::after, ::first-line, and ::first-letter) may, for legacy reasons, be represented using the <pseudo-class-selector> grammar, with only a single ":" character at their start.

For minimizing purpose we can covert `PseudoElemenetSelector` to `PseudoClassSelector`, we don't need visit all `PseudoSelector` nodes, because it will slow down.

Also `is:()` and etc selector can be converted to simple and versa vice:
```
p:is(.class, .other) { }
// ->
p.class, p.other { }
```

With some limitations, but we don't need to handle all `pseudo` selectors, because it will be slow too.

2021-11-15 11:00 UTC, alexander-akait commented
@kdy1 Can you review? Should I rebase?

2021-11-15 11:27 UTC, kdy1 commented
I'll review code changes, but rebase is required to be merged I think?

2021-11-15 11:30 UTC, alexander-akait commented
Yep, In my TODO, want to fix problems with `an+b` syntax in our pseudo classes today too

2021-11-15 11:51 UTC, kdy1 approved these changes
LGTM, thanks!

2021-11-15 11:52 UTC, kdy1 commented
(I looked at only code changes)

2021-11-15 22:57 UTC, alexander-akait commented
@kdy1 Ready for review, should be merged after https://github.com/swc-project/swc/pull/2759

2021-11-16 15:36 UTC, alexander-akait commented
@kdy1 Can you review? I have many good features :star: for selector parser

2021-11-18 13:24 UTC, alexander-akait commented
@kdy1 Can you review this, thanks

2021-11-19 08:54 UTC, kdy1 requested changes
Mostyle fine, thanks!

2021-11-19 08:54 UTC, kdy1 commented on crates/swc_css_parser/tests/fixture.rs
> +    fn visit_pseudo_class_selector(&mut self, s: &PseudoClassSelector, _: &dyn Node) {
I think we should also implement `visit_pseudo_element_selector` too.

2021-11-20 06:54 UTC, kdy1 approved these changes
Thanks!

2021-11-20 07:29 UTC, merged