fix(ecma/transforms): destructing arguments
swc-project/swc pull request #2904
Opened 2021-11-28 14:38 UTC by RiESAEX

fix #2841

2021-11-28 20:15 UTC, Austaras commented
I don't believe `arguments` should be handled specially here. Anything except an array literal should be transformed to `slice.call` in strict mode and `.slice()` in loose mode

2021-11-29 03:25 UTC, RiESAEX commented
> I don't believe `arguments` should be handled specially here. Anything except an array literal should be transformed to `slice.call` in strict mode and `.slice()` in loose mode
 
Several case for right side 
1. `ArrayExpression`: distribute value on compile time and `.slice`
2. `arguments` in function: `slice.call`
3. other: helper function:  `_toArray` (and `_maybeArrayLike` if assume array-like object is iterable)

may be related: [babel-plugin-transform-destructuring](https://babeljs.io/docs/en/babel-plugin-transform-destructuring#allowarraylike)

2021-11-29 04:34 UTC, Austaras commented
Yes, `new Array` and `Array.from` should also be considered

2021-11-29 09:35 UTC, kdy1 commented
I agree with @Austaras. Babel does not handle `arguments` specially, and we should not.


https://github.com/babel/babel/blob/23fec0c8c99a70b5739124dc2087a24f291b021e/packages/babel-plugin-transform-destructuring/src/index.ts

2021-11-29 10:43 UTC, kdy1 requested changes
Thanks!
I found a small performance issue.

2021-11-29 10:43 UTC, kdy1 commented on crates/swc_ecma_transforms_compat/src/es2015/destructuring.rs
> +                                    Expr::Call(CallExpr {
This seems inefficient.
Instead of creating a new box, I think creating `Box` here will be better.

2021-11-29 10:43 UTC, kdy1 commented on crates/swc_ecma_transforms_compat/src/es2015/destructuring.rs
> +                                    *right
Aften then, this can be just `r`.

2021-11-29 10:43 UTC, kdy1 commented on crates/swc_ecma_transforms_compat/src/es2015/destructuring.rs
> +                            _ => *right,
Also this can be modified to remove useless `memmove`.

2021-11-30 01:33 UTC, kdy1 commented on crates/swc_ecma_transforms_compat/src/es2015/destructuring.rs
> +                            right: match self.c.loose {
I think `if c.loose {} else {}` is better at here.

2021-11-30 01:34 UTC, kdy1 commented on crates/swc_ecma_transforms_compat/src/es2015/destructuring.rs
> +                                        match elems.iter().find(|elem| match elem {
I think `if iter.any() {}` is better than `match iter.find()` + `Some(_)`

2021-11-30 01:36 UTC, kdy1 requested changes
I found some code style issues.

2021-11-30 04:18 UTC, kdy1 approved these changes
LGTM, thanks!

2021-11-30 04:49 UTC, merged