refactor(es/transforms/compat): visit_mut for static_blocks
swc-project/swc pull request #2973
Opened 2021-12-05 06:28 UTC by kwonoj

Continuing #2370.

:Ez: one

I thought I picked file to continue https://github.com/swc-project/swc/pull/2966 but realized it's not after complete it. Anyway, this is small module so I took a stab before going back to #2966. PR applies few refactorings as visit_mut didn't need to follow strictly same path what fold does for this case.

2021-12-06 07:56 UTC, kdy1 requested changes
Thank you!

2021-12-06 07:56 UTC, kdy1 commented on crates/swc_ecma_transforms_compat/src/es2022/static_blocks.rs
> +        static_block: &mut StaticBlock,
I think it's better to take `StaticBlock` without reference, as we always `.take()` it.

2021-12-07 05:27 UTC, kdy1 approved these changes
LGTM. Thanks!

2021-12-07 06:18 UTC, merged

2021-12-07 07:40 UTC, sosukesuzuki commented
I've implemented static_blocks transformation and tried this refactoring in the past and gave up, thanks!

2021-12-07 07:47 UTC, kwonoj commented
@sosukesuzuki 👍