refactor(es/transforms/compat): visit_mut for class constructor
swc-project/swc pull request #2995
Opened 2021-12-08 11:24 UTC by RiESAEX

for #2370

2021-12-09 01:06 UTC, kwonoj commented on crates/swc_ecma_transforms_compat/src/es2015/classes/constructor.rs
>  /// TODO: VisitMut
may remove comments?

2021-12-09 01:06 UTC, kwonoj commented on crates/swc_ecma_transforms_compat/src/es2015/classes/constructor.rs
> +                    e.callee.map_with_mut(|callee| {
this is q for @kdy1 : when do we recommend direct assignment vs. map_with_mut? I used direct assignment in most cases mostly not knowing map_with_mut.

2021-12-09 01:06 UTC, kwonoj commented on crates/swc_ecma_transforms_compat/src/es2015/classes/constructor.rs
> +        // let arg = stmt.arg.to_owned();
unused comments?

2021-12-09 01:06 UTC, kwonoj commented on crates/swc_ecma_transforms_compat/src/es2015/classes/constructor.rs
> +                                call_args.extend(args.clone().into_iter());
are these need clone or if we can take?

2021-12-09 01:06 UTC, kwonoj commented on crates/swc_ecma_transforms_compat/src/es2015/classes/mod.rs
> +            constructor.body = constructor.body.fold_with(&mut as_folder(VarRenamer {
curios if these still need fold, or can do `ctor.body.visit_mut` instead?

2021-12-09 03:12 UTC, RiESAEX commented
@kwonoj Thanks!
I update most of them, excpet case of direct assignment vs. map_with_mut

2021-12-10 09:06 UTC, kdy1 requested changes
Thanks! I found some tiny issues.

2021-12-10 09:06 UTC, kdy1 commented on crates/swc_ecma_transforms_compat/src/es2015/classes/constructor.rs
> +        expr.map_with_mut(|expr| {
`map_with_mut` is same as using `Fold`.
(It's `memmove` anyway.)

2021-12-10 09:06 UTC, kdy1 commented on crates/swc_ecma_transforms_compat/src/es2015/classes/constructor.rs
> +                                call_args.extend(args.take().into_iter());
`.into_iter()` seems redundant.

2021-12-11 04:55 UTC, kdy1 requested changes
Almost LGTM, thanks!
I found one tiny issue about `Span`.

2021-12-11 04:55 UTC, kdy1 commented on crates/swc_ecma_transforms_compat/src/es2015/classes/constructor.rs
> +                    span: span.take(),
Can you change this to `span: *span`?
`Span` implements `Copy` so `.take()` is redundant.

2021-12-11 07:07 UTC, kdy1 approved these changes
LGTM/ Thank you!

2021-12-11 08:24 UTC, merged