refactor(es/ast): change ClassProp definition
swc-project/swc pull request #3038
Opened 2021-12-14 06:04 UTC by Austaras

**Description:**
make ClassProp key PropName

**BREAKING CHANGE:**
It will change the definition of ast tree

**Related issue (if exists):**
It will close #3026, and as an intended side effect, close #2516 and some unreported decorator issue

2021-12-14 09:33 UTC, kdy1 commented on crates/swc_ecma_codegen/src/lib.rs
> +        if n.key.is_computed() {
You can replace this with `emit!(n.key)`.
The emit method for `PropName` is aware of `Computed`.

2021-12-14 09:43 UTC, kdy1 requested changes
Mostly LGTM. Thank you!
Can you rebase this?

2021-12-14 14:23 UTC, Austaras commented
Done

2021-12-15 07:20 UTC, kdy1 approved these changes
Thanks!

2021-12-15 07:21 UTC, merged