feat(es/parser): parsing support for imports and exports with string names
swc-project/swc pull request #3048
Opened 2021-12-15 23:27 UTC by sosukesuzuki

# WORK IN PROGRESS

**Description:**

- Add parsing support for [imports and exports with string names](https://github.com/tc39/ecma262/pull/2154)

**BREAKING CHANGE:**

**Related issue (if exists):**

Fixes #3021 

**Todo:**

- [x] AST
- [ ] Parsing import specifiers
- [ ] Parsing export specifiers
- [ ] Tests

2022-01-01 16:05 UTC, sosukesuzuki commented
@kdy1 Hi, this PR is ready for review! This PR focuses on changing AST. Please see PR description for more details.

2022-01-01 19:42 UTC, kdy1 requested changes
I only partially reviewed as I expect some similar issues for changes in other crate.

2022-01-01 19:42 UTC, kdy1 commented on crates/swc_ecma_lints/src/rules/duplicate_exports.rs
> +                unimplemented!("module string names unimplemented")
This should not panic, as it will result in a failure of compilation.

2022-01-01 19:42 UTC, kdy1 commented on crates/swc_ecma_lints/src/rules/duplicate_exports.rs
> +                unimplemented!("module string names unimplemented")
I think `return` will be the most appropriate one.

2022-01-01 19:42 UTC, kdy1 commented on crates/swc_ecma_lints/src/rules/duplicate_exports.rs
> +            _ => unimplemented!("module string names unimplemented"),
Same here

2022-01-01 19:42 UTC, kdy1 commented on crates/swc_ecma_minifier/src/analyzer/mod.rs
> +            ModuleExportName::Str(..) => unimplemented!("module string names unimplemented"),
This should not panic because it will break whole transpilation.

2022-01-01 19:42 UTC, kdy1 commented on crates/swc_ecma_minifier/src/pass/mangle_names/analyzer/mod.rs
> +            ModuleExportName::Str(..) => unimplemented!("module string names unimplemented"),
Same here

2022-01-03 08:16 UTC, kdy1 approved these changes
Thank you! LGTM.

2022-01-03 08:16 UTC, kdy1 commented on crates/swc_bundler/src/bundler/chunk/cjs.rs
> +                            }
I used some time to think about this, but I concluded that panicking is fine for the bundler at the moment.

2022-01-03 08:16 UTC, kdy1 commented on crates/swc_bundler/src/bundler/chunk/cjs.rs
> +                            }
I'll fix this in near future.

2022-01-03 08:16 UTC, kdy1 commented on crates/swc_ecma_transforms_module/src/import_analysis.rs
> +                                unimplemented!("module string names unimplemented")
I'm bit worried by this, but I think we can implement this with another PR...

2022-01-03 08:44 UTC, merged