DRAFT: Ignore source maps in args in generated fns for classes
swc-project/swc pull request #3242
Opened 2022-01-12 11:08 UTC by 0xe

swc generates mappings in through identifiers passed as arguments in functions generated for providing class support such as _classCallCheck, _inherits. This PR implements changes to ignore these mappings.

Before:
<img width="387" alt="before" src="https://user-images.githubusercontent.com/35959/149129122-10e00e7d-c56e-4cdb-9057-a14876d64700.png">

After:
<img width="371" alt="after" src="https://user-images.githubusercontent.com/35959/149129142-d080e14a-6d21-4141-bf93-41a8d924ee7c.png">

2022-01-12 11:44 UTC, kdy1 requested changes
This can be done by giving `DUMMY_SP` to corresponding nodes instead.
We should not patch codegen to avoid generating sourcemap of some nodes.

2022-01-12 12:04 UTC, 0xe commented
> This can be done by giving `DUMMY_SP` to corresponding nodes instead. We should not patch codegen to avoid generating sourcemap of some nodes.

If I give DUMMY_SP for those nodes before clone it treats it as a new identifier. It generates this for example:

<img width="375" alt="gen" src="https://user-images.githubusercontent.com/35959/149137044-820dc192-b4a2-47f8-9613-2507a885b251.png">

2022-01-12 12:06 UTC, kdy1 commented
You should preserve the syntax context (`.span.ctxt`) of `Ident`. 
https://docs.rs/swc_ecma_ast/0.65.0/swc_ecma_ast/struct.Ident.html

2022-01-17 05:55 UTC, kdy1 requested changes
Thank you!

2022-01-17 05:55 UTC, kdy1 commented on crates/swc_ecma_transforms_compat/src/es2015/classes/mod.rs
> +                        args: vec![Expr::Ident(class_name_sym).as_arg()],
Please us `class_name_sym.as_arg()` instead of `Expr::Ident(class_name_sym).as_arg()`.

2022-01-17 06:22 UTC, kdy1 approved these changes
LGTM. Thank you!

2022-01-17 06:48 UTC, merged