feat(css/parser): `@layer` at-rule
swc-project/swc pull request #3258
Opened 2022-01-13 16:16 UTC by alexander-akait

**Description:**

`@layer` parsing https://www.w3.org/TR/css-cascade-5/#at-layer

**BREAKING CHANGE:**

Do we have it for CSS?

**Related issue (if exists):**

No

WIP

2022-01-13 22:25 UTC, kdy1 requested changes
Mostly LGTM, thanks!

I found an issue related to bitflags.

2022-01-13 22:25 UTC, kdy1 commented on crates/swc_css_codegen/src/list.rs
> +        DelimitersMask: SpaceDelimited | SemiDelimited | CommaDelimited | DotDelimited,
I think we should change value of`AllowTrailingComma` to `1 << 6`>

2022-01-14 11:00 UTC, alexander-akait commented
@kdy1 Fixed :+1:

2022-01-14 11:06 UTC, kdy1 approved these changes
LGTM. Thank you!

2022-01-14 11:21 UTC, merged