Fix important ast
swc-project/swc pull request #3440
Opened 2022-02-03 13:08 UTC by alexander-akait

**Description:**

Fix AST of `!important`, because `important` work is identifier we should use Ident AST node here, also it allows to parse and keep how important was written

**BREAKING CHANGE:**

Yes

**Related issue (if exists):**

No

2022-02-04 03:27 UTC, kdy1 requested changes
Thanks!

2022-02-04 03:27 UTC, kdy1 commented on crates/swc_stylis/src/prefixer.rs
> +                let important = match &n.important {
I think `n.important.clone()` would be better.

2022-02-04 03:27 UTC, kdy1 commented on crates/swc_stylis/src/prefixer.rs
> +                        let important = match &n.important {
Same here

2022-02-04 03:27 UTC, kdy1 commented on crates/swc_stylis/src/prefixer.rs
> +                            let important = match &n.important {
Same here.

2022-02-04 03:27 UTC, kdy1 commented on crates/swc_stylis/src/prefixer.rs
> +                            let important = match &n.important {
Same here.

2022-02-04 03:27 UTC, kdy1 commented on crates/swc_stylis/src/prefixer.rs
> +                let important = match &n.important {
Same here.

2022-02-04 03:27 UTC, kdy1 commented on crates/swc_stylis/src/prefixer.rs
> +                let important = match &n.important {
Same here.

2022-02-04 03:27 UTC, kdy1 commented on crates/swc_stylis/src/prefixer.rs
> +                let important = match &n.important {
Same here.

2022-02-05 13:53 UTC, alexander-akait commented
@kdy1 Done :+1:

2022-02-05 14:22 UTC, kdy1 approved these changes
LGTM. Thanks!

2022-02-05 14:22 UTC, merged