Feat nesting selectors
swc-project/swc pull request #3575
Opened 2022-02-15 14:24 UTC by alexander-akait

**Description:**
Features:

- Support parsing nested selectors https://www.w3.org/TR/css-nesting-1/
- Fix parsing of `@document`
- Use SimpleBlock for `@media` and `@supports`

**BREAKING CHANGE:**

Yes

**Related issue (if exists):**

No

2022-02-15 14:58 UTC, kdy1 commented
I'm not sure why CI fails with
```

error /home/runner/work/swc/swc/node_modules/csstree: Command failed.
```

2022-02-15 15:01 UTC, alexander-akait commented on package.json
> +        "css-tree": "^2.0.4",
Oh, it was just local test :smile: I will remove

2022-02-15 15:22 UTC, alexander-akait commented
@kdy1 Ready for review

2022-02-15 16:05 UTC, kdy1 requested changes
Can you revert yarn.lock?

2022-02-15 16:51 UTC, alexander-akait commented
@kdy1 Done

2022-02-16 03:39 UTC, kdy1 approved these changes

2022-02-16 03:40 UTC, merged