feat(es/lint): add no-bitwise rule implementation
swc-project/swc pull request #3635
Opened 2022-02-19 12:42 UTC by ArturAralin

**Description:**

add no-bitwise rule implementation

**BREAKING CHANGE:**
No

2022-02-19 12:43 UTC, ArturAralin commented on crates/swc_ecma_lints/src/rules/no_bitwise.rs
> +                            "&" => allow_binary_ops.insert(BinaryOp::BitAnd),
Possibly it's has better way to convert &str to enum

2022-02-20 04:08 UTC, kdy1 requested changes
Thank you! Mostly LGTM.

2022-02-20 04:08 UTC, kdy1 commented on crates/swc_ecma_lints/src/rules/no_bitwise.rs
> +                            "&" => allow_binary_ops.insert(BinaryOp::BitAnd),
Can you use `op!("&")` instead of `BinaryOp::BitAnd`?

2022-02-20 04:08 UTC, kdy1 commented on crates/swc_ecma_lints/src/rules/no_bitwise.rs
> +                            ">>>" => allow_binary_ops.insert(BinaryOp::ZeroFillRShift),
Also for these lines.

2022-02-20 04:08 UTC, kdy1 commented on crates/swc_ecma_lints/src/rules/no_bitwise.rs
> +                            "|=" => allow_assign_ops.insert(AssignOp::BitOrAssign),
And these lines.

2022-02-20 04:08 UTC, kdy1 commented on crates/swc_ecma_lints/src/rules/no_bitwise.rs
> +        if let UnaryOp::Tilde = &unary_expr.op {
Please use `op!` instead.

2022-02-21 01:55 UTC, kdy1 approved these changes
Thank you!

swc-bump:
 - swc_ecam_lints

2022-02-21 02:17 UTC, merged