feat: compress urange
swc-project/swc pull request #3668
Opened 2022-02-21 19:36 UTC by alexander-akait

**Description:**

Port - https://github.com/cssnano/cssnano/tree/master/packages/postcss-normalize-unicode + drop leading `0`

**BREAKING CHANGE:**

No

**Related issue (if exists):**

No

2022-02-22 08:17 UTC, kdy1 commented on crates/swc_css_minifier/src/compress/urange.rs
> +        for char in value.chars() {
Please use different name than `char`, which is a builtin type.
This distracts review process.

2022-02-22 12:58 UTC, alexander-akait commented
@kdy1 Ready for review

2022-02-22 13:01 UTC, kdy1 commented on crates/swc_css_minifier/src/compress/urange.rs
> +        for char in value.chars() {
This still applies

2022-02-22 13:05 UTC, alexander-akait commented
@kdy1 missed that :smile: Fixed

2022-02-22 15:11 UTC, alexander-akait commented
@kdy1 Rebased too

2022-02-22 15:37 UTC, kdy1 requested changes
Mostly LGTM.

I found one code style issue.

2022-02-23 08:20 UTC, kdy1 approved these changes
LGTM. Thank you!

---

swc-bump:
 - swc_css_minifier

2022-02-23 08:45 UTC, merged