fix: custom instanceof Handler result should be cast to boolean
swc-project/swc pull request #3728
Opened 2022-02-24 15:02 UTC by liby

**Description:** 
  - `helper.instanceof` does not cast `[Symbol.hasInstance]` call to boolean 

**Related issue (if exists):**
  - Closes #2836
  
 Also: If need to add a test case, please tell me how to do it, I may not know the situation.

2022-02-24 15:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/swc-project/swc?pullRequest=3728) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/swc-project/swc?pullRequest=3728) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/swc-project/swc?pullRequest=3728) it.</sub>

2022-02-25 01:41 UTC, kdy1 approved these changes
Thanks!

2022-02-25 02:03 UTC, kdy1 commented
Please run `UPDATE=1 cargo test` in the swc crate directory

2022-02-25 02:04 UTC, kdy1 requested changes
Marking as change requested

2022-02-25 02:49 UTC, liby commented
> Please run `UPDATE=1 cargo test` in the swc crate directory

 I didn't get any fails:
 ```
 test result: ok. 4185 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 16.71s

   Doc-tests swc

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

2022-02-25 02:59 UTC, kdy1 approved these changes

2022-02-25 02:59 UTC, kdy1 approved these changes
swc-bump:
 - swc_ecma_transforms_base

2022-02-25 03:08 UTC, liby commented
@kdy1 🙏 I would like to ask if I can run `update-all` to update the test after the fix is done? I don't see similar instructions in the contribution guide.

2022-02-25 03:11 UTC, kdy1 commented
Yes, I think the `update-all` script will update most of the fixtures.
It's not documented as it's added too recently.

2022-02-25 03:22 UTC, merged