feat(css/lints): Implement `no-duplicate-at-import-rules` rule
swc-project/swc pull request #3833
Opened 2022-03-03 16:32 UTC by g-plane

**Description:**

Implemented [`no-duplicate-at-import-rules`](https://stylelint.io/user-guide/rules/list/no-duplicate-at-import-rules/).

**BREAKING CHANGE:**

No.

2022-03-03 18:04 UTC, alexander-akait reviewed
Let's add tests with layer https://www.w3.org/TR/css-cascade-5/#at-import

2022-03-03 23:47 UTC, g-plane commented
Are we missing anything? Why do we mark this PR "work in progress"?

2022-03-03 23:48 UTC, kdy1 commented
Because of https://github.com/swc-project/swc/pull/3833#pullrequestreview-899319493

I marked it as a draft (WIP) because I don't want to poll PRs

2022-03-04 00:21 UTC, g-plane commented
@alexander-akait Are there any differences for the code below?

```css
@import "url.css" layer;
```

```css
@import "url.css" layer();
```

```css
@import "url.css" layer(default);
```

2022-03-05 14:16 UTC, g-plane commented
@alexander-akait Can you answer the question above? Thanks.

2022-03-06 13:57 UTC, alexander-akait commented
@g-plane Sorry for delay:
```css
@import "url.css" layer;
@import "url.css" layer();
```

are the same, but

```css
@import "url.css" layer(default);
@import "url.css" layer(other);
```

Are not, for example you can have:
```
@import "normalize.css" layer(framework);
@import "normalize.css" layer(my-library);
```

But in other hand our rule about duplication in URLs, and maybe we should report here anyway, that's a good question for discussion, currently I think we should always report about duplications, maybe we will revisit it late (will be great to open an issue in stylelint too, so that we can decide on a more correct behavior).

So right now let's add tests to ensure we always report about duplication with layer 

https://www.w3.org/TR/css-cascade-5/#cascading

2022-03-06 15:25 UTC, alexander-akait submitted a review, later dismissed

2022-03-06 23:46 UTC, g-plane commented
@kdy1 This can be reviewed now.

2022-03-07 03:16 UTC, kdy1 requested changes
Thank you!
I reviewed only rust code and I'll request review for css parts, as I don't know well about css

2022-03-07 03:16 UTC, kdy1 commented on crates/swc_css_lints/src/rules/no_duplicate_at_import_rules.rs
> +use ahash::AHashSet;
Please use `AHashSet` from `swc_common` instead.

2022-03-07 03:16 UTC, kdy1 commented on crates/swc_css_lints/src/rules/no_duplicate_at_import_rules.rs
> +use ahash::AHashSet;
(For consisstency.)

2022-03-07 03:16 UTC, kdy1 commented on crates/swc_css_lints/src/rules/no_duplicate_at_import_rules.rs
> +use ahash::AHashSet;
`ahash::AHashSet` and `ahash::AHashMap` are newtype structs, while those in `swc_common` is type alias for standard hashmap type.

2022-03-07 14:20 UTC, alexander-akait approved these changes

2022-03-07 19:24 UTC, kdy1 approved these changes
Thank you!

---

swc-bump:
 - swc_css_lints

2022-03-07 19:49 UTC, kdy1 requested changes
CI failed

2022-03-08 03:55 UTC, kdy1 approved these changes

2022-03-08 03:55 UTC, kdy1 commented
Can you rebase?

2022-03-08 03:56 UTC, kdy1 requested changes
There are some merge conflicts

2022-03-08 07:41 UTC, kdy1 approved these changes
LGTM. Thanks!

---

swc-bump:
 - swc_css_lints

2022-03-08 08:06 UTC, merged

2022-08-23 12:25 UTC, yisibl commented
> @alexander-akait Are there any differences for the code below?
> 
> ```css
> @import "url.css" layer;
> ```
> 
> ```css
> @import "url.css" layer();
> ```
> 
> ```css
> @import "url.css" layer(default);
> ```

`@import "url.css" layer();` is a wrong syntax. see https://github.com/w3c/csswg-drafts/pull/7601

2022-08-26 10:40 UTC, alexander-akait commented
@yisibl Can you open an issue?

2022-08-26 11:15 UTC, yisibl commented
> @yisibl Can you open an issue?

No problem: https://github.com/swc-project/swc/issues/5643