feat(css/minifier): compress import at-rule
swc-project/swc pull request #3839
Opened 2022-03-03 21:51 UTC by alexander-akait

**Description:**

Compress `@import` at-rule

**BREAKING CHANGE:**

No

**Related issue (if exists):**

No

2022-03-03 21:51 UTC, alexander-akait commented on crates/swc_css_minifier/src/lib.rs
> +    stylesheet.visit_mut_with(&mut compress_at_rule());
Looks like we do mistake when merge and we have two `compress_selector`

2022-03-03 21:59 UTC, kdy1 approved these changes
LGTM. Thanks!

---

swc-bump:
 - swc_css_minifier

2022-03-03 22:57 UTC, kdy1 requested changes
Clippy is angry again

2022-03-04 11:16 UTC, alexander-akait commented
Close in favor https://github.com/swc-project/swc/pull/3850

2022-03-04 11:16 UTC, closed without merging