fix-3885 report error if LeftHandSideExpression is invalid
swc-project/swc pull request #4001
Opened 2022-03-13 19:00 UTC by sahilmob

**Description:**
fixes #3885

**BREAKING CHANGE:**
None

**Related issue (if exists):**
#3885

2022-03-13 19:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/swc-project/swc?pullRequest=4001) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/swc-project/swc?pullRequest=4001) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/swc-project/swc?pullRequest=4001) it.</sub>

2022-03-13 19:18 UTC, kdy1 requested changes
Can you add some tests for this?

2022-03-14 17:25 UTC, sahilmob commented
I added a single test case against the reported issue.

2022-03-15 05:20 UTC, kdy1 reviewed
Thank you!


---


swc-bump:
 - swc_ecma_parser

2022-03-15 05:24 UTC, kdy1 approved these changes

2022-03-15 05:24 UTC, merged