Update line number start to 0
swc-project/swc pull request #4082
Opened 2022-03-18 19:30 UTC by edwincoronado

**Description:**
This fixes issue #4081 by starting line number at 0 instead of 1 since Miette increments the line.

**Related issue (if exists):**
#4081

2022-03-18 19:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/swc-project/swc?pullRequest=4082) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/swc-project/swc?pullRequest=4082) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/swc-project/swc?pullRequest=4082) it.</sub>

2022-03-19 04:43 UTC, kdy1 requested changes
This is wrong place to fix

2022-03-19 04:43 UTC, kdy1 requested changes
You should modify miette adapter instead

2022-03-19 06:41 UTC, edwincoronado commented
Updating failing tests.

2022-03-19 07:09 UTC, edwincoronado commented
@kdy1 do you know if there is a way of generating the `*.stderr` files programmatically? After running this in root directory:

`find . -name '*stderr' | wc -l`

I see that there's a total of 1084 files. Would be very time consuming to fix all manually.

2022-03-19 07:11 UTC, kdy1 commented
You can run `UPDATE=1 cargo test`
It's in contributing.md

2022년 3월 19일 (토) 오후 4:09, Edwin Coronado ***@***.***>님이 작성:

> @kdy1 <https://github.com/kdy1> do you know if there is a way of
> generating the *.stderr files programmatically? After running this in
> root directory:
>
> find . -name '*stderr' | wc -l
>
> I see that there's a total of 1084 files. Would be very time consuming to
> fix all manually.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/swc-project/swc/pull/4082#issuecomment-1072957840>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHELSJ7K5QPBEAL7OIQL5G3VAV4S7ANCNFSM5RCXCGHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-03-19 07:34 UTC, kdy1 requested changes
If you want, I can update test references for you

2022-03-19 07:34 UTC, kdy1 commented on crates/swc_error_reporters/src/lib.rs
> +            line: loc.line - 1,
Can you use `saturating_sub` instead?

2022-03-19 14:23 UTC, kdy1 commented on crates/swc_error_reporters/src/lib.rs
> +            line: loc.line - 1,
I'll update/merge this PR as this is required for other PRs

2022-03-19 14:33 UTC, kdy1 approved these changes, later dismissed
swc-bump:
 - swc_error_reporters

2022-03-19 14:43 UTC, kdy1 submitted a review, later dismissed

2022-03-19 14:56 UTC, merged