feat(es/lint): implement symbol-description rule
swc-project/swc pull request #4161
Opened 2022-03-25 13:33 UTC by ArturAralin

**Description:**

**BREAKING CHANGE:**

No

2022-03-25 15:52 UTC, kdy1 requested changes
Thank you!

2022-03-25 15:52 UTC, kdy1 commented on crates/swc_ecma_lints/src/rules/symbol_description.rs
> +                    return;
I think this will miss

```js
foo(() => Symbol())
```

2022-03-25 17:11 UTC, ArturAralin commented on crates/swc_ecma_lints/src/rules/symbol_description.rs
> +                    return;
Yes you right. Thx

2022-03-26 06:22 UTC, kdy1 approved these changes
Thank you!

---

swc-bump:
 - swc_ecma_lints

2022-03-26 06:49 UTC, merged