feat(css/ast): union all at-rules to one at-rule in AST
swc-project/swc pull request #4189
Opened 2022-03-29 23:42 UTC by alexander-akait

**Description:**

Union all at-rules in one `AtRule` structure.

WIP, need some perf improvement + fix code in another crates

**BREAKING CHANGE:**

Yes

**Related issue (if exists):**

No

2022-03-31 04:26 UTC, kdy1 requested changes

2022-03-31 04:26 UTC, kdy1 commented on crates/swc_css_ast/src/at_rule.rs
> +    pub media_type: Option<Ident>,
I think we need `#[serde(rename = "mediaType")]`

2022-03-31 04:26 UTC, kdy1 commented on crates/swc_css_ast/src/at_rule.rs
> +    #[tag("ColorProfileName")]
This is wrong.

2022-03-31 04:26 UTC, kdy1 commented on crates/swc_css_ast/src/at_rule.rs
> +    #[tag("ColorProfileName")]
It should be

```rust
#[tag("DashedIdent")]
#[tag("Ident")]
```

instead

2022-03-31 04:26 UTC, kdy1 commented on crates/swc_css_ast/src/at_rule.rs
> +    pub matching_functions: Vec<DocumentPreludeMatchingFunction>,
I found one more renaming issue

2022-03-31 04:26 UTC, kdy1 commented on crates/swc_css_ast/src/at_rule.rs
> +    #[tag("KeyframesName")]
Same here, it should be two tag

2022-04-01 04:15 UTC, kdy1 submitted a review, later dismissed
Thank you!


---

swc-bump:
 - swc_css_ast --breaking

2022-04-01 04:16 UTC, kdy1 commented
Can you fix clippy?
https://github.com/swc-project/swc/runs/5774452396?check_suite_focus=true

2022-04-01 10:03 UTC, alexander-akait commented
WIP on clippy

2022-04-01 11:53 UTC, merged