fix(es/parser) Report more rest errors
swc-project/swc pull request #4244
Opened 2022-04-04 14:31 UTC by hanneslund

**Description:**

I've tried to make reporting of CommaAfterRestElement and NonLastRestParam/TS1014 errors consistent.

I used `self.emit_err` but I noticed that `syntax_error!` is used in other NonLastRestParam errors, which one is preferred here?

**Related issue (if exists):**

closes #3676

2022-04-04 15:16 UTC, Austaras commented
`emit_err` is preferred, as it could report multiple error on one pass.

2022-04-05 00:59 UTC, alexander-akait commented
We have the same problem for codegen https://github.com/swc-project/swc/blob/main/crates/swc_ecma_codegen/src/lib.rs#L2172, if we will have AST without source code (for example from cache, stored as JSON) we will have problems with code generation, we have many workarounds in codebase for trailing commas, they are all not good solution.

So I think we need introduce `trailing_comma` (and store span value?) like do babel (and other parsers) https://astexplorer.net/#/gist/e217c98d3fe03741d03aa0bbe48e7047/48e674e14ccc25908e30d443566917096c827c88

And so we can solve more problems in this PR, because direction is right

2022-04-05 00:59 UTC, alexander-akait commented
We have the same problem for codegen https://github.com/swc-project/swc/blob/main/crates/swc_ecma_codegen/src/lib.rs#L2172, if we will have AST without source code (for example from cache, stored as JSON) we will have problems with code generation, we have many workarounds in codebase for trailing commas, they are all not good solution.

So I think we need introduce `trailing_comma` (and store span value?) like do babel (and other parsers) https://astexplorer.net/#/gist/e217c98d3fe03741d03aa0bbe48e7047/48e674e14ccc25908e30d443566917096c827c88

And so we can solve more problems in this PR, because direction is right

2022-04-05 13:22 UTC, hanneslund commented
@alexander-akait 
Are you thinking something like this?
```rust
pub struct ArrayLit {
    pub span: Span,
    pub trailing_comma: Option<Span>, // <---

    pub elems: Vec<Option<ExprOrSpread>>,
}
```

2022-04-05 15:34 UTC, alexander-akait commented
@hanneslund Yes, like do babel, it will allow to improve codegen too

2022-04-06 13:14 UTC, kdy1 requested changes
Thank you!

2022-04-06 13:14 UTC, kdy1 commented on crates/swc_ecma_parser/src/parser/mod.rs
> +    trailing_commas: HashMap<BytePos, Span>,
Please use `FxHashMap` from `rustc_hash` or `AHashMap` from `swc_common` intead.

2022-04-07 03:10 UTC, kdy1 approved these changes
Thank you!

---

swc-bump:
 - swc_ecma_parser

2022-04-07 03:43 UTC, merged