feat(html/minifier): compress default values of attributes
swc-project/swc pull request #4427
Opened 2022-04-25 02:05 UTC by alexander-akait

**Description:**

Compress default values.

There are two limitation (so they were not added in default):
1. Some attributes have `default` value in spec, but some browsers don't respect spec and use own values (Safari like it), so they were not added
2. Legacy attributes (like `align`/etc), the same problems for different browsers

In any case, there can be many them, I tried to collect the most popular

**BREAKING CHANGE:**

No

**Related issue (if exists):**

No

2022-04-25 10:25 UTC, kdy1 requested changes

2022-04-25 10:25 UTC, kdy1 commented on crates/swc_html_minifier/src/lib.rs
> +            _ if attribute.value.is_some()
I think we don't need if guard here

2022-04-25 10:25 UTC, kdy1 commented on crates/swc_html_minifier/src/lib.rs
> +            _ if attribute.value.is_some()
We can directly return the negated boolean for if-guard

2022-04-25 18:40 UTC, alexander-akait commented
@kdy1 Rebased and refactored

2022-04-25 23:12 UTC, kdy1 approved these changes
Thanks!

---

swc-bump:
 - swc_html_minifier

2022-04-26 04:59 UTC, alexander-akait commented
@kdy1 Rebased and tests fixed, ready to merge

2022-04-26 05:19 UTC, kdy1 approved these changes

2022-04-26 07:11 UTC, kdy1 reviewed
reset ci

2022-04-26 07:12 UTC, merged