feat(html/minifier): remove `javascript:` prefix
swc-project/swc pull request #4460
Opened 2022-04-27 20:00 UTC by alexander-akait

**Description:**

Remove unencessary `javascript:` prefix

**BREAKING CHANGE:**

No

**Related issue (if exists):**

No

2022-04-28 01:44 UTC, kdy1 approved these changes
Thanks!
---

swc-bump:
 - swc_html_minifier

2022-04-28 03:30 UTC, kdy1 requested changes
Can you rebase?

2022-04-28 18:20 UTC, alexander-akait commented
@kdy1 Rebased and fixed too

2022-04-29 03:18 UTC, kdy1 approved these changes

2022-04-29 03:19 UTC, merged