fix(helper): update _interopRequireWildcard
swc-project/swc pull request #4479
Opened 2022-04-29 07:49 UTC by RiESAEX

**Description:**
since we don't have `importInterop: "node"`, I didn't update to the latest version in babel.

**BREAKING CHANGE:**

**Related issue (if exists):**
fix #4284

2022-04-29 07:50 UTC, kdy1 requested changes
Can you update https://github.com/swc-project/swc/blob/48b427e403552f56cb4c26dfcd55d7c632a77781/packages/swc-helpers/src/_interop_require_wildcard.js too?

2022-04-29 07:59 UTC, RiESAEX commented
I guess you mean the file in swc_ecma_transforms_base?

2022-04-29 08:00 UTC, kdy1 commented
Ah, yes sorry

2022-04-29 08:09 UTC, RiESAEX commented on crates/swc_ecma_transforms_base/src/helpers/_interop_require_wildcard.js
> +export default function _interopRequireWildcard(obj) {
sorry, I just copy and paste it directly. removed.

2022-04-29 08:23 UTC, kdy1 approved these changes
Thank you!

---

swc-bump:
 - swc_ecma_transforms_base

2022-04-29 08:56 UTC, kdy1 commented
I'm not sure why we inline helper in the test, but can you update the test?

2022-04-30 00:56 UTC, kdy1 approved these changes

2022-04-30 00:56 UTC, merged