fix(html/parser): document mode and parsing
swc-project/swc pull request #4539
Opened 2022-05-05 17:12 UTC by alexander-akait

**Description:**

Fix bug due to my inattention when reading the specification

**BREAKING CHANGE:**

No

**Related issue (if exists):**

No

2022-05-06 04:08 UTC, kdy1 approved these changes
swc-bump:
 - swc_html_parser

2022-05-06 06:47 UTC, kdy1 requested changes
Please rebase

2022-05-06 14:14 UTC, alexander-akait commented
@kdy1 rebase :+1:

2022-05-07 05:53 UTC, kdy1 approved these changes

2022-05-07 06:30 UTC, merged