fix(html/parser): fix error reporting
swc-project/swc pull request #4644
Opened 2022-05-12 19:48 UTC by alexander-akait

**Description:**

Fix missing errors + improve errors reporting tests, we don't pass all of them currently, so I will fix them step by step, but we don't pass tests only for 90 tests from 2200+

**BREAKING CHANGE:**

No

**Related issue (if exists):**

No

2022-05-13 06:31 UTC, kdy1 requested changes
Can you rebase?

2022-05-13 14:29 UTC, alexander-akait commented
@kdy1 Done

2022-05-14 01:21 UTC, kdy1 approved these changes
Thanks!

---

swc-bump:
 - swc_html_parser

2022-05-14 01:22 UTC, kdy1 approved these changes

2022-05-14 01:43 UTC, merged