refact(es/react): proper scope finding for react refresh
swc-project/swc pull request #4649
Opened 2022-05-13 02:33 UTC by Austaras

**Description:**

**BREAKING CHANGE:**

**Related issue (if exists):**

2022-05-13 10:24 UTC, kdy1 commented on crates/swc_ecma_transforms_react/src/refresh/hook.rs
> +                .map(|id| current_mark.is_descendant_of(id.span.ctxt().outer()))
How does this work?

2022-05-13 10:24 UTC, kdy1 commented on crates/swc_ecma_transforms_react/src/refresh/tests.rs
> +                unresolved_mark
Seems like an inconsistent mark?

2022-05-14 05:47 UTC, kdy1 requested changes
Thanks! 
But I think this can error for files which has decorator and jsx.

decorator pass injects some variables and this pass will error in that case.

2022-05-14 05:50 UTC, Austaras commented
Could you give an example?

2022-05-14 05:53 UTC, kdy1 commented
Can you try the code below?

```typescript
class Ns {

}
namespace Ns {
    export const FOO = 1;
    
}

const a = (a) => {
    const useE = useEffect;
    return function useFoo() {
      useE(() => console.log(a), []);
      return useState(123);
    };
}
```

It does not have a decorator, but `typescript::strip` also injects some variables.

2022-05-14 06:05 UTC, Austaras commented
It generates
```js
class Ns {
}
(function(Ns1) {
    var FOO = Ns1.FOO = 1;
})(Ns || (Ns = {}));
const a = (a1)=>{
    var _s = $RefreshSig$();
    const useE = useEffect;
    return _s(function useFoo() {
        _s();
        useE(()=>console.log(a1)
        , []);
        return useState(123);
    }, "useE{}\nuseState{(123)}", false, function() {
        return [
            useE
        ];
    });
};
```
which seems good enough. If I get what you mean, seems like I need to ignore injected variables?

2022-05-14 06:08 UTC, kdy1 commented
Oh, you are right, my bad. I used playground to check if input injects `var`, but it's not done by `typescript::strip`.

Can you try

```ts


namespace Ns {
    export const FOO = 1;
    
}

const a = (a) => {
    const useE = useEffect;
    return function useFoo() {
      useE(() => console.log(a), []);
      return useState(123);
    };
}
```

this instead?

And yeah, those should be ignored, but we may attach syntax context to the scope node alternatively

2022-05-14 06:10 UTC, Austaras commented
> but we may attach syntax context to the scope node alternatively
This is definitely better

2022-05-14 08:25 UTC, Austaras commented
I've played with giving block syntax context but encountered other problems, maybe it could be done in another pr.

2022-05-15 03:29 UTC, kdy1 approved these changes
Thank you!


---

swc-bump:
 - swc_ecma_transforms_react

2022-05-15 03:51 UTC, merged