feat(swc/transform_module): support local scoped amd require
swc-project/swc pull request #4727
Opened 2022-05-20 23:51 UTC by kwonoj

**Description:**
PR attempts to close https://github.com/swc-project/swc/issues/4718. Following logics to `exports`, PR attempts to inject local scoped `require` for the modules.

This PR mimics what tsc does (https://www.typescriptlang.org/play?jsx=0&module=2#code/KYDwDg9gTgLgBAMwK4DsDGMCWEVwEYQQAUAlHAN4C+QA) which shadows global cjs `require` entirely, instead of trying to apply private ident to existing `require` inside of module. This also reduces mutation to all of idents to callexpr, and we can short-curcuit visitor as soon as find first ident to callexpr.

**BREAKING CHANGE:**

**Related issue (if exists):**

2022-05-20 23:52 UTC, kwonoj commented
same as https://github.com/swc-project/swc/pull/4726, original PR was coming from incorrect branch.

2022-05-21 14:41 UTC, kdy1 requested changes

2022-05-21 14:41 UTC, kdy1 commented on crates/swc_ecma_transforms_module/src/amd.rs
> +            .unwrap_or(private_ident!("require"));
This should be `unwrap_or_else`

2022-05-21 17:47 UTC, kwonoj commented on crates/swc_ecma_transforms_module/src/amd.rs
> +            .unwrap_or(private_ident!("require"));
Updated!

2022-05-21 17:50 UTC, kdy1 approved these changes
Thank you!

---

swc-bump:
 - swc_ecma_transforms_module

2022-05-21 18:32 UTC, merged