Split export statements in commonjs to fix hoisting
swc-project/swc pull request #4745
Opened 2022-05-23 06:42 UTC by smvv

Hi @kdy1 I would like to contribute to SWC and this PR could solve issue #3456.

However, I'm new to Rust (but have experience in JS compiler tech), and I would like to request early feedback regarding the PR.

For example, I would like to request feedback regarding:
1. the overall approach of splitting export declarations and moving those to the bottom.
2. what should we do with import statements? Can we freely move those to the top?
3. `todo()` statements left in the code.
4. I see new `_default` var declarations in the updated test files. I think this comes from `crates/swc_ecma_transforms_module/src/common_js.rs` and I've made a change to avoid the extra vars when `ModuleItem::ModuleDecl(ModuleDecl::ExportDefaultExpr(expr))` is used. Should I also look into the other var declarations, or can we postpone this to another issue/PR?
5. When should I use `DUMMY_SP` exactly as `span`?
 

**Description:**

This transformation will re-ordering the export declarations. The goal is to solve the ReferenceError problem when exports are referencing identifiers declared later in the code.

**BREAKING CHANGE:**

I would like to make the PR non-breaking, but it could be a breaking change as of now.

Note: I still want to remove all `dbg!()` and other commented code.

**Related issue (if exists):**
#4567

2022-05-23 06:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/swc-project/swc?pullRequest=4745) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/swc-project/swc?pullRequest=4745) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/swc-project/swc?pullRequest=4745) it.</sub>

2022-05-23 09:20 UTC, kdy1 commented
> 1. the overall approach of splitting export declarations and moving those to the bottom.

We can store it in a vector and append the content of the vector to the actual statements.

> 2. what should we do with import statements? Can we freely move those to the top?

Not sure. I don't know the specification.

> 3. `todo()` statements left in the code.

This is the exact thing bothering me these days. Technically it's a task of minifier, but we can't know if `exports.foo` in `exports.foo = void 0;` is side-effect-free.

I'm considering some new techniques, but I have to polish it and write a RFC.

> 4. I see new `_default` var declarations in the updated test files. I think this comes from `crates/swc_ecma_transforms_module/src/common_js.rs` and I've made a change to avoid the extra vars when `ModuleItem::ModuleDecl(ModuleDecl::ExportDefaultExpr(expr))` is used. Should I also look into the other var declarations, or can we postpone this to another issue/PR?

It can be postponed.

5. When should I use `DUMMY_SP` exactly as `span`?
 
If the compiler generate a span and in the case it does not come from user's source code, you should use `DUMMY_SP`.



Btw, thank you for the PR!

2022-05-23 09:26 UTC, magic-akari commented
@kdy1  I am working on the esbuild style module transformation.

2022-05-23 09:48 UTC, kdy1 commented
@magic-akari Cool!
Thank you and feel free to open a draft PR if you want.

I typically do it to prevent duplicate works, but not opening is fine anyway

2022-06-12 03:27 UTC, kdy1 requested changes
Thank you, and sorry for the late review

2022-06-12 03:27 UTC, kdy1 commented on crates/swc_ecma_transforms_module/src/hoist.rs
> +                    asserts: None,
I think this bound is not required?

2022-06-12 03:27 UTC, kdy1 commented on crates/swc_ecma_transforms_module/src/hoist.rs
> +                            ident: expr.ident.unwrap_or(private_ident!("_default")),
This invokes `private_ident` regardless of `expr.ident`.

2022-06-12 03:27 UTC, kdy1 commented on crates/swc_ecma_transforms_module/src/hoist.rs
> +                            ident: expr.ident.unwrap_or(private_ident!("_default")),
Please use `unwrap_or_else` instead

2022-06-12 03:27 UTC, kdy1 commented on crates/swc_ecma_transforms_module/src/hoist.rs
> +                            ident: expr.ident.unwrap_or(private_ident!("_default")),
Same here

2022-07-02 03:25 UTC, kdy1 commented
I think this can be closed, thanks to the new module transforms

2022-07-02 03:25 UTC, closed without merging