fix(html/codegen): HTML entities
swc-project/swc pull request #4782
Opened 2022-05-24 20:31 UTC by alexander-akait

**Description:**

Here:
- bug fix for entities in attribute value
- better compression entities

There is potential improvement for `&amp;` entity in text, I will implement it in another PR

**BREAKING CHANGE:**

No

**Related issue (if exists):**

No

2022-05-25 02:14 UTC, kdy1 requested changes

2022-05-25 02:14 UTC, kdy1 commented on crates/swc_html_codegen/src/lib.rs
> +                result.push_str(&String::from("&amp;"));
This should be `result.push_str("&amp;")`

2022-05-25 02:14 UTC, kdy1 commented on crates/swc_html_codegen/src/lib.rs
> +                result.push_str(&String::from("&amp;"));
This will allocate `&amp;` on heap and drop it right away

2022-05-25 02:14 UTC, kdy1 commented on crates/swc_html_codegen/src/lib.rs
> +                result.push_str(&String::from("&lt;"));
Same here

2022-05-25 02:14 UTC, kdy1 commented on crates/swc_html_codegen/src/lib.rs
> +                result.push_str(&String::from("&amp;"));
Same here

2022-05-25 02:14 UTC, kdy1 commented on crates/swc_html_codegen/src/lib.rs
> +                result.push_str(&String::from("&gt;"));
Same here

2022-05-25 02:14 UTC, kdy1 commented on crates/swc_html_codegen/src/lib.rs
> +            '\u{00A0}' => result.push_str(&String::from("&nbsp;")),
Same here

2022-05-25 02:14 UTC, kdy1 commented on crates/swc_html_codegen/src/lib.rs
> +                result.push_str(&String::from("&lt;"));
Same here

2022-05-25 02:14 UTC, kdy1 commented on crates/swc_html_codegen/src/lib.rs
> +            '"' if is_attribute_mode => result.push_str(&String::from("&quot;")),
Same here

2022-05-25 11:38 UTC, alexander-akait commented
@kdy1 I don't know how I overlooked this :smile: seems tired, rebased and fix + improvement with `String::with_capacity`

2022-05-26 01:44 UTC, alexander-akait commented
@kdy1 Rebased, looks like we have some bugs in minifier after enable cross testing, but I think we can merge it and I will fix them in other PRs they are easy

2022-05-26 14:46 UTC, alexander-akait commented
@kdy1 Ready to merge so I will continue fix bugs

2022-05-27 08:18 UTC, kdy1 approved these changes
Thanks!

---

swc-bump:
 - swc_html_codegen

2022-05-27 08:39 UTC, merged