feat(html/minifier): improve compress attributes
swc-project/swc pull request #4849
Opened 2022-05-30 18:43 UTC by alexander-akait

**Description:**

Based on spec

**BREAKING CHANGE:**

No

**Related issue (if exists):**

No

2022-05-30 22:29 UTC, kdy1 requested changes

2022-05-30 22:29 UTC, kdy1 commented on crates/swc_html_minifier/src/lib.rs
> +            value = "".to_string();
Please use `js_word!("")` instead

2022-05-30 23:46 UTC, alexander-akait commented
@kdy1 Fixed + fix bug + more attributes

2022-05-31 23:45 UTC, kdy1 approved these changes
Thanks!

---

swc-bump:
 - swc_html_minifier

2022-06-01 00:07 UTC, merged