refactor(swc/ecma_codegen): support sourcemapper
swc-project/swc pull request #4879
Opened 2022-06-04 13:31 UTC by kwonoj

**Description:**

This PR looses type requirement to `SourceMap` in codegen's emitter to accept traits (SourceMapper + SourceMapperExt) instead.

Primarily this allows to any arbitary implementation to sourcemap to work with codegen's emitter - such as plugin can use emitter with `PluginSourceMapProxy` instead of host implementation. To achieve this, there were some adjustment as well such as bubbling up listformat to common package.

I've tried suggested approach as well, which makes `Emitter` accepts `Option<Sourcemap>` to allow to emit without sourcemapper implementation. It sort works, quickest, but there are inconsistencies when sourcemap is available vs. not vs. supplying `default` to the emitter for the actual output results. Seems like few paths rely on the sourcemapper creates those differences. 

PR aims to create `identical` behavior for the any sourcemapper implementation argument. This brings consistency when using emitter in any context (host vs plugin). This is bit important if a plugin visitor want to use codegen / emitter internally to ensure it'll behave same either if it's being used in custom pass, or inside of a plugin context.

**BREAKING CHANGE:**

**Related issue (if exists):**

2022-06-04 21:15 UTC, kwonoj commented
Updated PR with missing commits to support snap_to_snippet properly.

2022-06-05 05:26 UTC, kdy1 requested changes
Please move it to `swc_ecma_ast`, if it's really required

2022-06-05 05:26 UTC, kdy1 commented on crates/swc_common/src/source_map.rs
> +    list::ListFormat,
We should not have `ListFormat` in `swc_common`

2022-06-05 06:33 UTC, kwonoj commented
Ok, tried to adjust export to use ecma_ast instead. I hoped if there's way to preserve location of listformat, but it doesn't look like I can cut import chain easily to move sourcemapperext only.

2022-06-05 06:41 UTC, kdy1 commented
Why is `SourceMapperExt` aware of `ListFormat`? Sounds like there's a fundamental issue

2022-06-05 06:43 UTC, kwonoj commented
I don't have good historical context how it is composed - only thing I can say is currently sourcemappext / spanext both are tightly copuled with listformat for most of the implementation. (https://github.com/swc-project/swc/pull/4879/files#diff-e55f8cb04960b61fbd39aa6bcfa4cbecfb736780d09c2a7b4659a3376fec3a7eR25)

2022-06-05 07:32 UTC, kwonoj commented
(Clarifying : I didn't change implementation, only location's changed to allow use in proxy as well.)

2022-06-05 14:16 UTC, kdy1 approved these changes
Thanks!

---

swc-bump:
 - swc_common
 - swc_ecma_ast --breaking
 - swc_ecma_proxy --breaking

2022-06-05 14:40 UTC, merged