fix(css/parser): lexer errors
swc-project/swc pull request #5025
Opened 2022-06-22 03:14 UTC by alexander-akait

**Description:**

Add lexer errors for CSS parser.

We need to sort them in test because when we consume using tokens we run the lexer firstly and then the parser, but when we parser using string we lazy consume tokens, so errors have different order.

**BREAKING CHANGE:**

No

**Related issue (if exists):**

No

2022-06-22 04:05 UTC, kdy1 requested changes
Thank you!
`#[inline(always)]` makes debug build slower, and for error reporting functions, `#[cold]` is better

2022-06-22 04:05 UTC, kdy1 commented on crates/swc_css_parser/src/lexer/mod.rs
> +    #[inline(always)]
Can you remove this and instead add `#[cold]`?

2022-06-22 14:34 UTC, alexander-akait commented
@kdy1 Fixed, also fixed `for swc_html_parser`

2022-06-23 03:03 UTC, kdy1 approved these changes
Thank you!

---

swc-bump:
 - swc_css_parser

2022-06-23 03:56 UTC, merged