feat(es/module): add pure_annotations to interop functions
swc-project/swc pull request #5087
Opened 2022-07-02 03:35 UTC by magic-akari

**Description:**

**BREAKING CHANGE:**

**Related issue (if exists):**

2022-07-02 03:39 UTC, magic-akari commented on crates/swc/tests/fixture/issues-2xxx/2964/case-2/output/index.ts
> +}; /*#__PURE__*/
unexpected result. Maybe fixed by #5082

2022-07-02 03:39 UTC, magic-akari commented on crates/swc/tests/fixture/issues-2xxx/2964/case-3/output/index.ts
> + /*#__PURE__*/
same here.

2022-07-02 03:39 UTC, magic-akari commented on crates/swc/tests/fixture/issues-2xxx/2964/case-5/output/index.ts
> +} /*#__PURE__*/ );
same here.

2022-07-03 04:30 UTC, kdy1 requested changes
Thank you!

2022-07-03 04:30 UTC, kdy1 commented on crates/swc_ecma_transforms_module/src/umd.rs
> +        let span = Span::dummy_with_cmt();
I think this should go into the `if let` block below because `Span::dummy_with_cmt` is a heavy operation

2022-07-03 04:30 UTC, kdy1 commented on crates/swc_ecma_transforms_module/src/common_js.rs
> +        let span = Span::dummy_with_cmt();
Same here

2022-07-03 04:30 UTC, kdy1 commented on crates/swc_ecma_transforms_module/src/amd.rs
> +        let span = Span::dummy_with_cmt();
Same here

2022-07-03 05:22 UTC, kdy1 approved these changes
Thank you!

---

swc-bump:
 - swc_ecma_transforms_module --breaking

2022-07-03 05:54 UTC, merged