feat(swc/node): interop swc/wasm for bindings
swc-project/swc pull request #5233
Opened 2022-07-17 06:34 UTC by kwonoj

**Description:**

- closes https://github.com/swc-project/swc/issues/5221

PR includes 2 changes:

1. Introduce `postinstall` to silently install `@swc/wasm` if native binding cannot be loaded
There's no good way to specify fallback dependencies if all of optional dependency installation fails. A naive postinstall script does validation of installation, then installs `@swc/wasm` as fallback if native binary cannot be loaded.

To reduce burden of installation pkg for the features only will be used for rare cases of fallback, postinstall script doesn't try to use own dependencies to resolve & download pkg but relies on system's npm directly. 

2. Binding falls back to `@swc/wasm`

In actual bindings, if native binding is not available it'll try to import `@swc/wasm` and interop its interface if @swc/wasm have corresponding one. If there aren't, it'll transparently fail.

**BREAKING CHANGE:**

**Related issue (if exists):**

2022-07-17 06:39 UTC, kdy1 approved these changes
Thanks!

---

swc-bump:
 - ''

2022-07-17 06:39 UTC, kdy1 requested changes
CI failed

2022-07-17 07:35 UTC, kwonoj commented
CI's now good to go, though this is a bit tricky to test, so we may need to see a couple of releases to see if there are some regressions.

2022-07-17 09:05 UTC, kdy1 approved these changes

2022-07-17 09:33 UTC, merged

2022-07-20 09:20 UTC, sinceresiva commented
Hi,
Let me give the background for reference. Grafana v9.0.3 is using a previous version of @swc/core which was giving the "Unsupported Architecture" error in IBM z-Linux (s390x) machines. I have now changed the Grafana package.json to use the latest version of @swc/core **v1.2.218**. Now I get a different error "Bindings not found" as show in the error in below screenshot (on executing: yarn start). From the current PR **swc** is supposed to interop between @swc/core and @swc/wasm. Am I missing any additional step? Pls help.
<img width="479" alt="image" src="https://user-images.githubusercontent.com/4971391/179944864-705176cc-5fc7-4d69-8ce0-12500c6c9194.png">
My environment is:
OS: IBM z-Linux (s390x)
NodeJS version: v16.15.1
yarn version: 4.0.0-rc.12
npm version: 8.11.0

2022-07-27 13:54 UTC, kwonoj commented on node-swc/src/postinstall.ts
> +      { cwd: installDir, stdio: 'pipe', env });
This is the way esbuild does for fallback as well : https://github.com/evanw/esbuild/blob/54ebf0cc7f7580e9b290a5a225ae8c784745d45f/lib/npm/node-install.ts#L97