feat(css/minifier): remove duplicate selectors
swc-project/swc pull request #5257
Opened 2022-07-20 01:56 UTC by alexander-akait

**Description:**

Remove duplicate selectors

**BREAKING CHANGE:**

No

**Related issue (if exists):**

No

2022-07-20 03:48 UTC, kdy1 requested changes
Iterating over hashmap is slow

2022-07-20 03:48 UTC, kdy1 commented on crates/swc_css_minifier/src/compress/selector.rs
> +        let mut already_seen: AHashSet<ComplexSelector> = Default::default();
This should be a vector instead

2022-07-25 14:54 UTC, alexander-akait commented
@kdy1 Fixed :+1:

2022-07-26 01:28 UTC, kdy1 approved these changes
Thanks!

---

swc-bump:
 - swc_css_minifier

2022-07-26 01:55 UTC, merged