fix(css/prefixer): generate at-rules based on env
swc-project/swc pull request #5294
Opened 2022-07-25 15:57 UTC by alexander-akait

**Description:**

Don't generate unnecessary `at-rules` based on `env`

**BREAKING CHANGE:**

No

**Related issue (if exists):**

No

2022-07-26 04:54 UTC, kdy1 requested changes
Thanks!

2022-07-26 04:54 UTC, kdy1 commented on crates/swc_css_prefixer/src/prefixer.rs
> +    fn add_at_rule(&mut self, prefix: Prefix, at_rule: AtRule) {
I think `at_rule` should be `&AtRule`

2022-07-26 04:54 UTC, kdy1 commented on crates/swc_css_prefixer/src/prefixer.rs
> +                            block: original_simple_block.clone(),
So we clone only if required

2022-07-26 12:22 UTC, alexander-akait commented
@kdy1 Fixed :+1:

2022-07-27 04:01 UTC, kdy1 approved these changes
Thanks!

---
swc-bump:
 - swc_css_prefixer

2022-07-27 04:43 UTC, merged