feat(swc/core): implement engine diagnostics
swc-project/swc pull request #5515
Opened 2022-08-16 18:48 UTC by kwonoj

**Description:**

This PR is second attempt to https://github.com/swc-project/swc/pull/5501 . 

Relying on build script time git info is not something we want - since `build` can occur when binary try to import `swc_core`. What we need is pre-baked in constants when `swc_core` is published. PR still try to use vergen for some optional values, but for the git sha it uses a more direct approach to generate sha when publish script running.

**BREAKING CHANGE:**

**Related issue (if exists):**

2022-08-17 02:10 UTC, kdy1 requested changes
I think this will not work if I publish crates locally

2022-08-17 02:11 UTC, kwonoj commented
> I think this will not work if I publish crates locally

yes indeed. how frequent we do manual publish?

2022-08-17 02:13 UTC, kdy1 commented
I don't have concrete number, but it's quite frequent

2022-08-17 02:15 UTC, kwonoj commented
I may be wrong, but I think there's no good way to satisfy all the cases if we want to physically embed some constants. Any suggestions? Or just accept it for some releases by bailing out and emitting default placeholder string instead?

2022-08-17 02:26 UTC, kdy1 commented
We can generate the dummy file from build script instead.

> Or just accept it for some releases by bailing out and emitting default placeholder string instead

Yeah

2022-08-17 02:28 UTC, kwonoj commented
> dummy file from build script instead.

Vergen is essentially this and it reveals thing I didn't thought of : if plugin user want to use swc_core, it is built from cargo cache and not for the git repo so it failed to build it further.

2022-08-17 02:33 UTC, kdy1 commented
Then we should remove git hash.
The crate version is enough

2022-08-17 02:36 UTC, kwonoj commented
This pr will serve git has as 'opportunistic', as it'll likely include but in case of local / manual it may not. 

Thoughts on making it as `Option` instead to reflect it better? Then it'll be an additional metadata but can miss sometimes.

2022-08-17 02:37 UTC, kdy1 commented
Why is git hash required?
If we know the version, we can know know the git hash by looking at the version.

Note that this PR will break publishing as cargo really hates non-commited files

2022-08-17 02:40 UTC, kdy1 commented
That's why we have data json files for preset-env commited in the repository.
I tried generating it from CI, but cargo rejected it.

2022-08-17 02:42 UTC, kdy1 commented
Alternative way is to have it commited in the repository by storing it in the `prepare` script.
If we do so, crate publish CI action will update it everytime, although it would be one-off

2022-08-17 02:42 UTC, kwonoj commented
1. We had already know cases version does not include changes we 'thought' we included in. Basically version is non deterministic way to check snapshot of changes.
2. It still can be retrieved by look through git has as you said, but in combination of 1 above it requires amount of manual process each time. 

For the publish, current generated script creates one off dummy commit to remove dirty state but not oush it to origin to not to leak those into git history.

I think the need of hash maybe debatable, but for me it was helpful to bisect regressions in most cases.

2022-08-17 02:47 UTC, kdy1 approved these changes
Okay, sounds reasonable so let's try.

---

swc-bump:
 - swc_core

2022-08-18 03:25 UTC, kdy1 requested changes
Threre's a conflict

2022-08-18 04:28 UTC, kdy1 approved these changes

2022-08-18 04:29 UTC, merged