build(cargo): remove redundant packages
swc-project/swc pull request #5516
Opened 2022-08-16 19:28 UTC by kwonoj

**Description:**
We can remove these packages as it is no longer referenced (and update readme's published).

**BREAKING CHANGE:**

**Related issue (if exists):**

2022-08-17 02:07 UTC, kdy1 requested changes
We still need `swc_ecmascript`

2022-08-17 02:09 UTC, kwonoj commented
> We still need swc_ecmascript

Yes, will revert. Is there way we can announce & instruct migrate into swc_core for the users of swc_ecmascript?

2022-08-17 02:11 UTC, kdy1 commented
We need to add more to `swc_core` before removing it.
See `lib.rs` of `swc_ecmascript`

2022-08-17 02:16 UTC, kdy1 commented
About migration, we can do same thing like `swc_ecma_quote`

2022-08-17 02:17 UTC, kwonoj commented
Fwiw, swc_core already have ecma_quote support.

2022-08-17 02:23 UTC, kdy1 commented
I don't mean `swc_core` lacks it. `swc_ecmascript` has much more deps

2025-02-26 11:42 UTC, kdy1 commented
Closing as stale

2025-02-26 11:42 UTC, closed without merging