chore(es/preset-env): upgrade preset_env_base
swc-project/swc pull request #5534
Opened 2022-08-17 17:23 UTC by pan93412

**Description:**

This commit manages to specify the latest preset_env_base explicitly,
to not use the older preset_env_base which
did not include “bun“ and something new.

**BREAKING CHANGE:**

**Related issue (if exists):**
Related: #5293
Fixed: #5490

2022-08-17 17:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/swc-project/swc?pullRequest=5534) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/swc-project/swc?pullRequest=5534) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/swc-project/swc?pullRequest=5534) it.</sub>

2022-08-17 17:25 UTC, pan93412 commented
0.2.4 is new enough to fix this issue: <https://rustdoc.swc.rs/preset_env_base/struct.BrowserData.html>

2022-08-17 18:26 UTC, kdy1 requested changes
This will not have any effect.
See https://github.com/swc-project/swc/blob/1bdf6a7385c890dbfaedac773180d754f9f99a0b/bindings/Cargo.lock#L1585-L1601

2022-08-18 01:52 UTC, pan93412 commented
> This will not have any effect. See
> 
> https://github.com/swc-project/swc/blob/1bdf6a7385c890dbfaedac773180d754f9f99a0b/bindings/Cargo.lock#L1585-L1601

Weird. However, maybe this commit can invalidate the cache that may pick the older `preset_env_base` version?

2022-08-18 01:54 UTC, kdy1 commented
Oh I found the cause.
https://docs.rs/preset_env_base/latest/preset_env_base/struct.BrowserData.html

I'll publish a new version of that crate

2022-08-18 01:54 UTC, pan93412 commented
> Oh I found the cause. https://docs.rs/preset_env_base/latest/preset_env_base/struct.BrowserData.html
> 
> I'll publish a new version of that crate

Understand, thanks! I'll close this PR.

2022-08-18 01:54 UTC, closed without merging

2022-08-18 01:55 UTC, kdy1 commented
Thank you for investigating