feat(css/parser): make `keyword` optional
swc-project/swc pull request #5543
Opened 2022-08-18 00:55 UTC by alexander-akait

**Description:**

`keyword` is like `raw` required only for linter, but we don't need to spend time on it in transformations

**BREAKING CHANGE:**

Yes

**Related issue (if exists):**

No

2022-08-18 03:27 UTC, kdy1 approved these changes
Thanks!

---

swc-bump:
 - swc_css_ast --breaking

2022-08-18 05:13 UTC, kdy1 requested changes
There's a conflict

2022-08-19 17:18 UTC, alexander-akait commented
@kdy1 Fixed :+1:

2022-08-20 01:48 UTC, kdy1 approved these changes
Thanks!

2022-08-20 01:49 UTC, merged