Feat compress media and supports
swc-project/swc pull request #5828
Opened 2022-09-12 00:01 UTC by alexander-akait

**Description:**

Compress `@media` and `@supports` better

**BREAKING CHANGE:**

No

**Related issue (if exists):**

No

2022-09-12 08:06 UTC, kdy1 requested changes
Thanks!

2022-09-12 08:06 UTC, kdy1 commented on crates/swc_css_minifier/src/compressor/media.rs
> +                                    for new_item in iter {
Please use `new_conditions.extend(iter)` instead

2022-09-12 08:06 UTC, kdy1 commented on crates/swc_css_minifier/src/compressor/media.rs
> +                                for new_item in iter {
Same here

2022-09-12 08:06 UTC, kdy1 commented on crates/swc_css_minifier/src/compressor/media.rs
> +                                for new_item in iter {
Same here

2022-09-12 08:06 UTC, kdy1 commented on crates/swc_css_minifier/src/compressor/media.rs
> +                                    for new_item in iter {
Same here

2022-09-12 08:21 UTC, kdy1 requested changes

2022-09-12 08:21 UTC, kdy1 commented on crates/swc_css_minifier/src/compressor/supports.rs
> +                                    for new_item in iter {
Same here

2022-09-12 13:55 UTC, alexander-akait commented
@kdy1 Fixed :+1:

2022-09-12 13:55 UTC, alexander-akait commented
@kdy1 Fixed :+1:

2022-09-13 01:40 UTC, kdy1 reviewed
Can we check if it's optimizable before creating a new vector?
The current logic performs allocations and `memmove` without a good reason

2022-09-13 02:44 UTC, alexander-akait commented
@kdy1 Done :+1: Now we avoid extra allocations and memmove

2022-09-13 03:01 UTC, kdy1 commented on crates/swc_css_minifier/src/compressor/media.rs
> +                            if let Some(MediaConditionAllType::MediaInParens(media_in_parens)) =
This will drop first node if the pattern does not match

2022-09-13 03:01 UTC, kdy1 commented on crates/swc_css_minifier/src/compressor/media.rs
> +                                if let Some(MediaConditionAllType::MediaInParens(media_in_parens)) =
Same here

2022-09-13 03:30 UTC, alexander-akait commented
@kdy1 Added `is_first_supports_in_parens` and `is_first_media_in_parens` checks, so `else` is unreachable now

2022-09-13 03:37 UTC, kdy1 approved these changes
Thanks!

---

swc-bump:
 - swc_css_minifier

2022-09-13 04:43 UTC, merged