refactor(css/parser): improve structure
swc-project/swc pull request #6110
Opened 2022-10-10 20:39 UTC by alexander-akait

**Description:**

Improve structure

**BREAKING CHANGE:**

No

**Related issue (if exists):**

No

2022-10-11 03:15 UTC, kdy1 approved these changes
Thanks!

---
swc-bump:
 - swc_css_parser

2022-10-11 13:03 UTC, kdy1 requested changes
There's a merge conflict

2022-10-17 23:18 UTC, alexander-akait commented
@kdy1 Rebased :+1:

2022-10-18 01:12 UTC, kdy1 approved these changes

2022-10-18 01:41 UTC, merged