feat(css/parser): improve selector AST
swc-project/swc pull request #6112
Opened 2022-10-10 23:58 UTC by alexander-akait

**Description:**

Resolve TODO + tests + improve AST

**BREAKING CHANGE:**

Yes

**Related issue (if exists):**

No

2022-10-11 00:01 UTC, alexander-akait commented on crates/swc_css_codegen/tests/fixture/values/ident/output.min.css
> +:root{--fg-color:blue;--fg-\color-other:blue}.box{background-color:rebeccapurple;background-color:var(--fg-color);border-radius:10px;width:100px;height:100px}.box:hover{animation-name:rotate\ rotate;
Original code:
```css
\*|*{color:blue}
```

According spec it is `\*` namespace (so we print it as ident). 

Chrome has bug here `\*|*{color:blue}` parsed as `*{color:blue}`, firefox doesn't affected this bug and just can't parse it.

And both wrong here, chrome should not parse this as any namespace, firefox should parse this with `\*` namespace :smile: I will report this in both browsers

2022-10-11 13:03 UTC, kdy1 requested changes
There's a merge conflict

2022-10-11 13:08 UTC, alexander-akait commented
@kdy1 Yeah, I will fix it soon

2022-10-11 14:51 UTC, alexander-akait commented
@kdy1 Rebased :+1:

2022-10-12 01:41 UTC, kdy1 commented
Is this necessary? I think this may make working with AST harder

2022-10-12 02:19 UTC, alexander-akait commented
@kdy1 Yep, `*` is not the `Ident`, it is the special thing (any namespace), anyway it should simplify using AST for manipulation, because now you can easy to catch all `Any` namespace (minify purposes and svg minification), but namespace is not popular in current CSS, also here a small perf improvement too

2022-10-12 02:26 UTC, kdy1 approved these changes
swc-bump:
 - swc_css_ast --breaking

2022-10-12 02:57 UTC, merged