fix(css/modules): Fix parsing and interference
swc-project/swc pull request #6128
Opened 2022-10-12 07:41 UTC by kdy1

**Description:**

This PR fixes parsing of css modules and fixes interference with nesting css transform.

**Related issue:**

2022-10-12 11:13 UTC, kdy1 reviewed
swc-bump:
 - swc_atoms
 - swc_css_parser --breaking

2022-10-12 16:50 UTC, alexander-akait commented on crates/swc_css_parser/src/parser/base.rs
>  }
It is not valid solution...

2022-10-12 16:51 UTC, alexander-akait commented on crates/swc_css_parser/src/parser/selector/mod.rs
> +        }
We can't use it here, otherwise another pseudo will not work

2022-10-12 16:52 UTC, alexander-akait commented on crates/swc_css_parser/src/parser/selector/mod.rs
> +                let selectors = self.parse_as::<SelectorList>()?;
Inside `local` and `global` is not `SelectorList`, it is not valid to use `a, b` inside `:local`, because every local contain only compound selector

2022-10-12 16:55 UTC, alexander-akait requested changes
Give me some time to investigate it, because I really don't want to vilolate spec and have a lot of workarounds by it

2022-10-13 03:18 UTC, kdy1 commented
Closing as it's fixed by https://github.com/swc-project/swc/pull/6132

2022-10-13 03:18 UTC, closed without merging