feat(css/minifier): Handle nested `calc()`
swc-project/swc pull request #6153
Opened 2022-10-14 14:28 UTC by ghostd

**Description:**

Handle nested `calc()`:
`calc(100% - calc(50% + 25px))` => `calc(50% + 25px)`

**BREAKING CHANGE:**

**Related issue (if exists):**

2022-10-14 15:11 UTC, alexander-akait commented on crates/swc_css_minifier/tests/fixture/compress-calc/discard-zero/output.min.css
> +.class1{width:calc(100vw/2 - 6px)}.class2{width:500px}.class3{width:calc(0 - 10px)}.class4{width:calc(0 - 1px - 1em)}.class5{width:calc(0 - (100vw - 10px)/2)}.class6{width:calc(10px - 100vw)}.class7{
`width:calc(0 - 1px - 1em)` -> `width:calc(-1px - 1em)`

2022-10-14 15:16 UTC, alexander-akait requested changes
nested `calc()` is like (` and `)` , so I think we should handle it not in `transform_calc_value_into_component_value`, we should handle them inside calculation.

2022-10-15 11:46 UTC, ghostd commented
@alexander-akait 'im not sure to understand your comment, i added the "nested calc" handling into the `resume` function. I rebased, i hope the diff will be more readable.

2022-10-17 09:31 UTC, alexander-akait approved these changes
Great, there are some impvomenets more, like `width:calc(2.25rem - 0px)`, but let's do it another PR, because it is not related to nested `calc`

2022-10-17 09:31 UTC, alexander-akait commented
@kdy1 Ready to review

2022-10-17 10:18 UTC, kdy1 approved these changes
Thanks!

---

swc-bump:
 - swc_css_minifier

2022-10-17 12:08 UTC, merged

2022-10-17 18:57 UTC, ghostd commented
@alexander-akait i'll work on removing zeroes this week.

2022-10-17 19:00 UTC, alexander-akait commented
Thanks