feat(html/minifier): improve the `remove_redundant_attributes` option
swc-project/swc pull request #6197
Opened 2022-10-18 17:47 UTC by alexander-akait

**Description:**

Due https://github.com/kangax/html-minifier/issues/1075

A lot of CSS frameworks use (and not only):
```
input[type=text] {
  /* styles */
}
```

So it is not safe to remove them by default, anyway I implemented the `safe` mode - it will remove:
- deprecated attributes (they doesn't used in CSS almost always, expect very old frameworks, which already doesn't supported)
- SVG attributes, it  is common ptractide don't use them in CSS
- attributes from metadata elements, because they will not be rendered

**BREAKING CHANGE:**

Yes

**Related issue (if exists):**

No

2022-10-19 05:20 UTC, kdy1 requested changes

2022-10-19 05:20 UTC, kdy1 commented on crates/swc_html_minifier/src/option.rs
> +pub enum RemoveRedundantAttributes {
Let's implement `Default` for this type instead of using `#[serde(default = "")]`.

2022-10-19 05:20 UTC, kdy1 commented on crates/swc_html_minifier/src/option.rs
> +pub enum RemoveRedundantAttributes {
You can then change `#[serde(default = "...")]` to `#[serde(default)]`

2022-10-19 18:32 UTC, alexander-akait commented
@kdy1 Done, for another enum too :+1:

2022-10-19 23:29 UTC, kdy1 requested changes
CI faileda

2022-10-19 23:39 UTC, alexander-akait commented
@kdy1 Fixed again :smile:

2022-10-20 03:48 UTC, kdy1 approved these changes

2022-10-20 03:48 UTC, kdy1 approved these changes
swc-bump:
 - swc_html_minifier --breaking

2022-10-20 04:17 UTC, merged