feat(css/minifier): merge rules
swc-project/swc pull request #6220
Opened 2022-10-20 15:39 UTC by alexander-akait

**Description:**

Merge the same rules + all tests from https://github.com/cssnano/cssnano/tree/master/packages/postcss-merge-rules

**BREAKING CHANGE:**

No

**Related issue (if exists):**

partial https://github.com/swc-project/swc/issues/5880, there are two todos to solve all cases:
- future browserslist support
- partial merging rules (will be iin near future)

2022-10-21 00:05 UTC, kdy1 commented on crates/swc_css_minifier/src/compressor/rules.rs
> +                    right.span.span_lo(),
I think this is a mistake?

2022-10-21 00:18 UTC, alexander-akait commented on crates/swc_css_minifier/src/compressor/rules.rs
> +                    right.span.span_lo(),
Yeah, typo, need fix

2022-10-21 02:47 UTC, kdy1 approved these changes
swc-bump:
 - swc_css_minifier

2022-10-21 02:47 UTC, kdy1 commented on crates/swc_css_minifier/src/compressor/rules.rs
> +                    right.span.span_lo(),
I fixed it

2022-10-21 03:38 UTC, kdy1 requested changes
CI failed

2022-10-21 11:43 UTC, kdy1 requested changes
Can you rebase again to exclude unrelated commits?

2022-10-21 11:44 UTC, alexander-akait commented
@kdy1 Yeah, WIP on this, my mistake

2022-10-21 12:12 UTC, alexander-akait commented
@kdy1 Fixed

2022-10-21 12:49 UTC, kdy1 approved these changes

2022-10-21 12:49 UTC, merged

2022-10-24 12:35 UTC, ludofischer commented
Does the method in this PR also solve the various issues with the merge-rules implementation in cssnano (https://github.com/cssnano/cssnano/projects/5)?

2022-10-24 15:36 UTC, alexander-akait commented
@ludofischer we don't implement the partial merging and browserslist based, so we don't have these problems right now (but yes, we will need to solve them in future)