refactor(css/parser): refactor more
swc-project/swc pull request #6251
Opened 2022-10-25 13:52 UTC by alexander-akait

**Description:**

Refactor parser more

**BREAKING CHANGE:**

No, but AST is changed

**Related issue (if exists):**

No

2022-10-25 13:54 UTC, alexander-akait commented on crates/swc_css_parser/tests/recovery/hacks/output.swc-stderr
> - 226 | .selector { [;property: value;]; }
Avoid duplicate errors, we already reported about it above

2022-10-26 01:06 UTC, alexander-akait commented
@kdy1 Ready for review

2022-10-26 02:41 UTC, kdy1 requested changes

2022-10-26 02:41 UTC, kdy1 commented on crates/swc_css_parser/tests/recovery/at-rule/font-face/span.rust-debug
> + 17 | @font-face foo {}
I think this should be skipped

2022-10-26 10:21 UTC, kdy1 approved these changes
swc-bump:
 - swc_css_ast

2022-10-26 10:22 UTC, merged