fix(html/minifier): remove empty script and style with attributes
swc-project/swc pull request #6447
Opened 2022-11-15 15:47 UTC by alexander-akait

**Description:**

Remove empty script and style tags with default options

**BREAKING CHANGE:**

No

**Related issue (if exists):**

No

2022-11-15 22:56 UTC, kdy1 approved these changes
swc-bump:
 - swc_html_minifier

2022-11-15 22:57 UTC, kdy1 requested changes
CI failed

2022-11-15 23:35 UTC, alexander-akait commented
@kdy1 Fixed, just clippy

2022-11-16 17:56 UTC, alexander-akait commented
@kdy1 rebased and ready for review

2022-11-17 00:55 UTC, kdy1 approved these changes

2022-11-17 01:22 UTC, merged