Upgrade `browserslist-rs`
swc-project/swc pull request #6488
Opened 2022-11-21 02:30 UTC by jaydenseric

**Description:**

Upgrades the `browserslist-rs` dependency.

Importantly, `browserslist-rs` v0.12 marked Internet Explorer as dead:

https://github.com/browserslist/browserslist-rs/releases/tag/v0.12.0

**BREAKING CHANGE:**

Not sure if this is a breaking change, because browserslist queries are supposed to have different results over time. Most likely this PR could be considered a bug fix, because people expect the browserslist query to match the current spec and behavior.

**Related issue (if exists):**

N/A.

2022-11-21 02:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/swc-project/swc?pullRequest=6488) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/swc-project/swc?pullRequest=6488) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/swc-project/swc?pullRequest=6488) it.</sub>

2022-11-21 02:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/swc-project/swc?pullRequest=6488) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/swc-project/swc?pullRequest=6488) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/swc-project/swc?pullRequest=6488) it.</sub>

2022-11-21 02:33 UTC, kwonoj requested changes
We need https://github.com/browserslist/browserslist-rs/pull/13 change before upgrading brwoserslists-rs.

2022-11-21 16:56 UTC, kwonoj commented
/cc @g-plane for the visibility.

2022-12-01 02:26 UTC, kdy1 commented
Closes as this is fixed by #6547

2022-12-01 02:26 UTC, closed without merging