Feat css minifier port initial
swc-project/swc pull request #6613
Opened 2022-12-09 20:45 UTC by alexander-akait

**Description:**

port of https://github.com/cssnano/cssnano/tree/master/packages/postcss-reduce-initial

**BREAKING CHANGE:**

Yes, due AST changes

**Related issue (if exists):**

No

2022-12-10 01:31 UTC, kdy1 requested changes
Thank you!
`eq_ignore_ascii_case` is faster than comparison after `to_ascii_lowercase`

2022-12-10 01:31 UTC, kdy1 commented on crates/swc_css_minifier/src/compressor/declaration.rs
> +                if value.to_ascii_lowercase() == js_word!("initial") {
Let's use `value.eq_ignore_ascii_case(js_word!("initial"))` instead

2022-12-10 01:31 UTC, kdy1 reviewed
swc-bump:
 -  swc_atoms
 -  swc_css_ast --breaking

2022-12-11 16:05 UTC, alexander-akait commented
WIP on perf :+1:

2022-12-11 16:13 UTC, alexander-akait commented
@kdy1 Ready for review

2022-12-12 01:55 UTC, kdy1 approved these changes
Thanks!

2022-12-12 02:36 UTC, merged