feat(css/prefixer): font-face format
swc-project/swc pull request #6644
Opened 2022-12-13 21:00 UTC by alexander-akait

**Description:**

Port https://preset-env.cssdb.org/features/#font-format-keywords

**BREAKING CHANGE:**

No

**Related issue (if exists):**

No

2022-12-13 21:01 UTC, alexander-akait commented on crates/swc_css_prefixer/tests/fixture/font-face-format/output.css
> +  src: format(url("woff"));
Weird bug, WIP

2022-12-13 22:14 UTC, alexander-akait commented on crates/swc_css_prefixer/tests/fixture/font-face-format/output.css
> +  src: format(url("woff"));
Found a bug :smile: fixed

2022-12-14 01:45 UTC, kdy1 approved these changes
swc-bump:
 - swc_css_prefixer

2022-12-14 01:45 UTC, kdy1 requested changes
Merged failed

2022-12-14 13:21 UTC, alexander-akait commented
@kdy1 Rebased and fixed

2022-12-14 13:32 UTC, kdy1 commented on crates/swc_css_prefixer/src/prefixer.rs
> +            let new_value: JsWord = ident.value.clone().to_ascii_lowercase();
I think this `clone()` is redundant

2022-12-14 13:42 UTC, kdy1 approved these changes
Thank you!

2022-12-14 15:05 UTC, merged