Refactor do not use raw in codegen
swc-project/swc pull request #6674
Opened 2022-12-18 18:58 UTC by alexander-akait

**Description:**

Refactor codegen and do not use `raw`, also:
1. fix bug with printing `e\32px` dimension (we need to escape as in spec)
2. do not parser wrong hash token as color

**BREAKING CHANGE:**

Yes, we don't use `raw` in codegen, except printing tokens, so if you want to inject something non standard, you should use `ListOfComponentValues` with `PreservedToken`

**Related issue (if exists):**

No

2022-12-19 06:33 UTC, kdy1 commented on crates/swc_css_ast/src/base.rs
> +    IdSelector(Box<IdSelector>),
Is this change really required?

2022-12-19 15:55 UTC, alexander-akait commented
@kdy1 Rebased too

2022-12-20 07:59 UTC, kdy1 submitted a review, later dismissed
swc-bump:
 - swc_css_ast --breaking

2022-12-20 15:25 UTC, alexander-akait commented
@kdy1 Rebased too

2022-12-21 02:59 UTC, kdy1 requested changes
CI failed

2022-12-21 14:15 UTC, alexander-akait commented
@kdy1 Fixed too :+1:

2022-12-22 01:35 UTC, kdy1 approved these changes

2022-12-22 01:36 UTC, merged