feat(es/minifier): Improve simplification of `??`
swc-project/swc pull request #6681
Opened 2022-12-19 06:36 UTC by kdy1

**Description:**

**Related issue:**

 - Closes https://github.com/swc-project/swc/issues/6492.

2022-12-19 06:40 UTC, kdy1 reviewed
swc-bump:
 - swc_ecma_minifier

2022-12-19 06:41 UTC, kdy1 commented on crates/swc_ecma_minifier/tests/fixture/issues/6492/output.js
> +console.log('val', 42);
[Previous output](https://play.swc.rs/?version=1.3.23&code=H4sIAAAAAAAAA0vOzysuUchPylKwVahWSEvMS660UjAxUqi15koGS5Ul5gClgArs9aLzSnNyFGpqFNTB6tRjwUryc1L1cvLTNdSBKtV1QOo1AfhU17pVAAAA&config=H4sIAAAAAAAAA21TS7IbIQy8C2svUl5k8Q6QXVY5AIVBjPUyoCkk%2FDzlenePmLEZj50darob%2FbiZT%2Fbm42YmVxhKO%2FGcxV3Nh5F5AvYFJzEHI6yQlArfei4uc6SSGr2A87IcahZMoEJXhZIT9KrDNFGRP1SLb1fTSj%2BYABcYaUqQ5e7bjF0ZQGMDfPxxPCptJGLVRTcyHEzCjHFuj3lKasXcziqqzYc7z5VCX7z6HsyJaATN%2BDW2ji1mgQHKJvU0jm5isBdXuqK95goy5R1UBYKdCk1PaA4oSFnNHlgAF6ynAB3AAl7wAhtFPZSSWRPrmSxggFMdhjaYlQkXN1Yn3QuuSxv0xa47E7LYWDO%2FQLtMV2gt8s7CaAtILfnB%2BSTMuz78BdA8R8ecXYJNueBR57Bnxv%2BwMEcdoswd1QlvWWUYtDiLGHuFLWsoglu3CoTqoVXoN%2FM7uCuIMYCFGLXbXcxfKP68mbUlp9hD7ZqL2wzW0D72aY%2B2FXgDf2lW8jyOO67%2F4fyK8ZxONL5ZJJAzhTdYGyH0Chbd3uv0itYcQNsM4emicgv7murwhewIsvVZF0I1dhjp1NdXP2Vyeehr2X5polAbcFuat%2FzWn%2BZ7%2B52rH%2FLvO2%2Fx%2BQd0Pd7PaQQAAA%3D%3D)

2022-12-20 05:03 UTC, jridgewell requested changes
Nit: The PR title references optional coalescing `??`, but this is improving optional chaining `?.`.

2022-12-20 05:03 UTC, jridgewell commented on crates/swc_ecma_minifier/tests/fixture/issues/6492/input.js
> +const val = obj?.[null || 'key']
Can we include a few deeper variations?

```js
obj?.key.toString()
obj?.key?.toString()
obj.key?.toString()
```

2022-12-20 07:27 UTC, kdy1 commented on crates/swc_ecma_minifier/tests/fixture/issues/6492/input.js
> +const val = obj?.[null || 'key']
I'll do, thanks!

2022-12-20 07:51 UTC, jridgewell approved these changes

2022-12-20 09:34 UTC, merged