feat(css/parser): normalize urange
swc-project/swc pull request #6704
Opened 2022-12-21 15:04 UTC by alexander-akait

**Description:**

There are:
- lowercase characters
- implement `raw` if you want to use our parser as linter or for another 1:1 parsing purposes
- fix bug with remove duplications of uranges (we don't merge before when you have `u` and `U` prefixes, i.e. different case)

**BREAKING CHANGE:**

Yes

**Related issue (if exists):**

No

2022-12-22 01:40 UTC, kdy1 approved these changes
I'll rollup css AST changes

---

swc-bump:
 - dbg-swc

2022-12-22 01:41 UTC, kdy1 requested changes
Merge conflict

2022-12-27 11:14 UTC, alexander-akait commented
@kdy1 Fixed and rebased too

2022-12-27 12:16 UTC, kdy1 approved these changes

2022-12-27 12:22 UTC, merged