refact(es/minifier): merge `cond_init` with `reassigned`
swc-project/swc pull request #6850
Opened 2023-01-25 06:20 UTC by Austaras

**Description:**

And optimize following sutiation
```js
export function genElement(el, state) {
    if ('slot' === el.tag) return el1 = el, genChildren(el1);
    if (el.component) {
        var el1
        return 999;
    }
}
```
which rarely happens in hand written JS, but is often generated by swc merge variable pass

**BREAKING CHANGE:**

**Related issue (if exists):**

2023-01-25 07:33 UTC, kdy1 requested changes
Thank you!

---

swc-bump:
 - swc_ecma_usage_analyzer --breaking

2023-01-25 07:33 UTC, kdy1 commented on crates/swc_ecma_usage_analyzer/src/analyzer/mod.rs
> +                        println!("function");
Please remove this

2023-01-25 07:33 UTC, kdy1 commented on crates/swc_ecma_usage_analyzer/src/analyzer/mod.rs
> +                        println!("functionend");
And this

2023-01-25 07:33 UTC, kdy1 commented on crates/swc_ecma_usage_analyzer/src/analyzer/mod.rs
> +        println!("blockend");
Also this

2023-01-25 07:33 UTC, kdy1 commented on crates/swc_ecma_usage_analyzer/src/analyzer/mod.rs
> +        println!("block");
Also this

2023-01-25 07:33 UTC, kdy1 commented on crates/swc_ecma_minifier/src/program_data.rs
> +            println!("init {}", i.sym);
Also this

2023-01-25 17:49 UTC, jridgewell approved these changes

2023-01-26 01:17 UTC, kdy1 approved these changes
Thanks!

2023-01-26 01:17 UTC, merged