feat(ec/parser): Add disallow_ambiguous_jsx_like option to parse mts and cts files like tsc and babel
swc-project/swc pull request #6913
Opened 2023-02-07 13:10 UTC by nissy-dev

**Description:** Add `disallow_ambiguous_jsx_like` option to parse mts and cts files like tsc and babel.

**BREAKING CHANGE:**

**Related issue (if exists):** Part of #4679 I also referred to https://github.com/babel/babel/pull/13838

2023-02-28 06:07 UTC, kdy1 commented
Can you rebase?

2023-03-01 16:49 UTC, nissy-dev commented
I rebased!

2023-03-02 02:34 UTC, kdy1 requested changes

2023-03-02 02:34 UTC, kdy1 commented on crates/swc_ecma_parser/src/lib.rs
> +    pub fn disallow_ambiguous_jsx_like(self) -> bool {
Please make this not public

2023-03-02 03:48 UTC, kdy1 commented on crates/swc_ecma_parser/src/lib.rs
> +    pub fn disallow_ambiguous_jsx_like(self) -> bool {
```suggestion
   fn disallow_ambiguous_jsx_like(self) -> bool {
```

2023-03-03 01:59 UTC, kdy1 approved these changes
Thanks!

---

swc-bump:
 - swc_ecma_parser --breaking

2023-03-03 02:47 UTC, merged