test(swc): Add Bazel tests
swc-project/swc pull request #6933
Opened 2023-02-11 11:04 UTC by realtimetodie

Adds an integration test that simulates a Bazel environment using symbolic links to sources.

Related

- https://github.com/swc-project/swc/pull/6930

2023-02-11 13:19 UTC, kdy1 submitted a review, later dismissed
Thank you so much!

---
swc-bump:
 - dbg-swc

2023-02-11 13:20 UTC, kdy1 commented
Oh CI failed

2023-02-11 13:45 UTC, realtimetodie commented
This can only be merged after #6930.

2023-02-13 04:31 UTC, kdy1 requested changes
Honestly, I'm not sure if this should be treated as a valid test case.
Does tsc work in this way? I'm going to patch `jsc.paths` to match one of tsc soon, and I think this test case can interfere it.

2023-02-13 04:31 UTC, kdy1 commented on crates/swc/tests/projects.rs
> +                return ();
Please remove this line

2023-02-13 04:31 UTC, kdy1 commented on crates/swc/tests/projects.rs
> +        let _ = remove_file(symlink_source_path.clone());
This clone is redundant

2023-02-13 04:31 UTC, kdy1 commented on crates/swc/tests/projects.rs
> +        let _ = remove_file(symlink_source_path.clone());
```suggestion
        let _ = remove_file(&symlink_source_path);
```

2023-02-13 04:31 UTC, kdy1 commented on crates/swc/tests/projects.rs
> +        let _ = remove_file(symlink_build_path.clone());
```suggestion
        let _ = remove_file(&symlink_build_path);
```

2023-02-13 04:31 UTC, kdy1 commented on crates/swc/tests/projects.rs
> +            symlink(src_dir, symlink_build_path.clone()).unwrap();
Same here

2023-02-13 04:31 UTC, kdy1 commented on crates/swc/tests/projects.rs
> +            symlink(modules_dir, symlink_source_path).unwrap();
Same here

2023-02-13 04:31 UTC, kdy1 commented on crates/swc/tests/projects.rs
> +            symlink_dir(src_dir.clone(), symlink_build_path.clone()).unwrap_or_else(|_| {
Same here

2023-02-13 04:37 UTC, closed without merging