compress: Fix unsound optimization of `new RegExp(…)`
swc-project/swc pull request #7091
Opened 2023-03-16 07:41 UTC by andersk

In #4932, an optimization was added that transforms `new RegExp(…)` to `RegExp(…)`.  It seems to have been motivated by this sentence in the ECMAScript specification:

> Thus the function call `RegExp(…)` is equivalent to the object creation expression `new RegExp(…)` with the same arguments.

But that sentence turns out to be wrong.  It contradicts the detailed steps in the following section of the specification, as well as the empirical behavior of JavaScriptCore, SpiderMonkey, and V8:

    > r = /a/;
    /a/
    > RegExp(r) === r
    true
    > new RegExp(r) === r
    false

Restrict this optimization to the case where we can prove one of the first two arguments is a string.

Fixes #6941.

2023-03-16 10:54 UTC, kdy1 requested changes
swc-bump: 
 - swc_ecma_minifier

2023-03-16 10:54 UTC, kdy1 commented on crates/swc_ecma_minifier/src/compress/pure/misc.rs
> +fn can_compress_new_regexp(args: &Option<Vec<ExprOrSpread>>) -> bool {
```suggestion
fn can_compress_new_regexp(args: Option<&[ExprOrSpread]>) -> bool {
```

2023-03-16 10:54 UTC, kdy1 commented on crates/swc_ecma_minifier/src/compress/pure/misc.rs
> +                && can_compress_new_regexp(args)) =>
```suggestion
                && can_compress_new_regexp(args.as_deref())) =>
```

2023-03-16 18:03 UTC, andersk commented on crates/swc_ecma_minifier/src/compress/pure/misc.rs
> +fn can_compress_new_regexp(args: &Option<Vec<ExprOrSpread>>) -> bool {
Done.

2023-03-17 01:22 UTC, kdy1 approved these changes
Thank you!

---

swc-bump:
 - swc_ecma_minifier

2023-03-17 03:22 UTC, merged