feat: commonjs support import interop function at rust side
swc-project/swc pull request #7134
Opened 2023-03-23 12:28 UTC by underfin

**Description:**

**BREAKING CHANGE:**

**Related issue (if exists):**
https://github.com/swc-project/swc/issues/7130

2023-03-23 12:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/swc-project/swc?pullRequest=7134) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/swc-project/swc?pullRequest=7134) before we can accept your contribution.<br/><hr/>**likui** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/swc-project/swc?pullRequest=7134) it.</sub>

2023-03-23 12:33 UTC, kdy1 requested changes

2023-03-23 12:33 UTC, kdy1 commented on crates/swc_ecma_preset_env/data/core-js-compat/data.json
Please revert this

2023-03-23 12:43 UTC, underfin commented on crates/swc_ecma_transforms_module/src/common_js.rs
> +    import_interop_fn: ImportInteropFn,
Add it to `Config` will need impl trait for `Debug/Clone`, look like it is not good.

2023-03-23 13:09 UTC, kdy1 commented on crates/swc_ecma_transforms_module/src/common_js.rs
> +    import_interop_fn: ImportInteropFn,
Oh, I see.

2023-03-23 13:41 UTC, kdy1 commented
No worries, it's automatic 😄 .
All changes in the main swc repository are published each time a PR is merged

2023-03-23 23:12 UTC, kdy1 commented
I discussed about this with the team, and we concluded not to accept this change. I'm sorry, but I want to be more careful about adding apis. (And I hate breaking changes)

2023-03-23 23:12 UTC, closed without merging

2023-03-24 03:41 UTC, underfin commented
`Please move this field to config with #[serde(skip_deserializing)]`

If add `import_interop_fn` to `Config` without api change, maybe you like it?

2023-03-24 03:46 UTC, kdy1 commented
No, it's still an API change.

2023-03-24 04:31 UTC, underfin commented
What do you think about this?
```
pub enum ImportInterop {
    #[serde(alias = "babel")]
    Swc,
    Node,
    None,
    Fn(ImportInterOpFn)
}
```

2023-03-24 04:50 UTC, kwonoj commented
Debate in here is if we want / expose fn, or another object as an additional way to current api surface, How is the second problem. So far we only had 1 feature request, where we are not able to determine if it is being widely used among swc users, or either there are strong needs that resolves wide ecosystem problem. The original issue does not addresses neither.

Since last year, along with the sdk (swc_core) and its consumer (swc/core, next-swc) we are trying to move towards stable, manageable narrow api surface to control over. There are some historical decisions made early which made swc's current state bit complex - that's something we want to reduce but also not easy, however adding  / expanding new feature / api surface is something we can control & we are trying to do now.