fix: Resolve the error of missing map file.
swc-project/swc pull request #7141
Opened 2023-03-24 09:38 UTC by limerickgds

**Description:** When there is no sourcemap file, an error occurs because the file path with .map added automatically cannot be found.

**BREAKING CHANGE:** no

**Related issue (if exists):**

2023-03-27 12:13 UTC, limerickgds commented
@kdy1 Please help review this.

2023-03-28 02:07 UTC, kdy1 requested changes
Can you add a test for this?

2023-03-28 02:44 UTC, limerickgds commented
> Can you add a test for this?

@kdy1 done

2023-03-29 03:15 UTC, kdy1 requested changes

2023-03-29 03:15 UTC, kdy1 commented on crates/swc/src/lib.rs
> +                                            .context("failed to open input source map file");
This `context` is redundant

2023-03-29 03:15 UTC, kdy1 commented on crates/swc/src/lib.rs
> +                                    PathBuf::from(format!("{}.map", filename.display()));
Can we be lazy here? This allocation is not necessary.

2023-04-02 03:16 UTC, kdy1 approved these changes
swc-bump:
 - swc

2023-04-02 03:47 UTC, merged