fix(es/loader): fix browser overwrites not applying correctly
swc-project/swc pull request #7243
Opened 2023-04-10 21:03 UTC by icewind1991

- es/loader: add test for browser overwrite
- es/loader: fix browser overwrites

**Description:**

Fix browser `main` overwrites from `package.json` not working when specified like

```json
{
  "name": "jquery",
  "main": "./index.js",
  "browser": {
    "./index.js": "./browser.js"
  }
}
```

Found in the wild in [solidjs](https://github.com/solidjs/solid/blob/main/packages/solid/web/package.json#L5)

This was mainly broken due to a mix of absolute and relative paths being compared.

2023-04-10 21:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/swc-project/swc?pullRequest=7243) <br/>All committers have signed the CLA.

2023-04-10 21:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/swc-project/swc?pullRequest=7243) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/swc-project/swc?pullRequest=7243) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/swc-project/swc?pullRequest=7243) it.</sub>

2023-04-11 02:11 UTC, kdy1 requested changes
Thanks!

---

swc-bump: 
 - swc_ecma_loader

2023-04-11 02:11 UTC, kdy1 commented on crates/swc_ecma_loader/src/resolvers/node.rs
> +                                    dbg!(pkg_dir, k);
Please remove this line

2023-04-11 02:11 UTC, kdy1 commented on crates/swc_ecma_loader/src/resolvers/node.rs
> +                            dbg!(path);
Ditto

2023-04-11 12:18 UTC, icewind1991 commented on crates/swc_ecma_loader/src/resolvers/node.rs
> +                                    dbg!(pkg_dir, k);
oops :see_no_evil:

2023-04-11 13:08 UTC, kdy1 approved these changes
Thanks!

---

swc-bump:
 - swc_ecma_loader

2023-04-14 23:48 UTC, merged