fix: Const module default imports
swc-project/swc pull request #7604
Opened 2023-06-29 13:09 UTC by liaoyinglong

Fixes #7601

**Description:**

**BREAKING CHANGE:**

**Related issue (if exists):**

2023-06-29 13:37 UTC, kdy1 requested changes

2023-06-29 13:37 UTC, kdy1 commented on crates/swc_ecma_transforms_optimization/src/const_modules.rs
> +                                let default_import_key = JsWord::from("default");
```suggestion
                                let default_import_key = js_word!("default");
```

2023-06-29 14:35 UTC, liaoyinglong commented on crates/swc_ecma_transforms_optimization/src/const_modules.rs
> +                                let default_import_key = JsWord::from("default");
updated

2023-06-30 02:12 UTC, kdy1 approved these changes
Thanks!

---


swc-bump:
 - swc_ecma_transforms_optimization

2023-06-30 02:12 UTC, merged