fix(es/compat): Visit transformed expression in optional chaining pass
swc-project/swc pull request #7614
Opened 2023-07-03 02:49 UTC by kdy1

**Description:**

**Related issue:**

 - Closes #7612.

2023-07-03 02:50 UTC, kdy1 reviewed
swc-bump:
 - swc_ecma_transforms_compat

2023-07-03 18:05 UTC, jridgewell requested changes

2023-07-03 18:05 UTC, jridgewell commented on crates/swc/tests/fixture/issues-7xxx/7612/input/1.js
> +}
Nit: this is enough to trigger the bug:
```suggestion
(qcData?.flawImageList || [])?.map()
```

2023-07-03 18:05 UTC, jridgewell commented on crates/swc_ecma_transforms_compat/src/es2020/optional_chaining.rs
> +                e.visit_mut_children_with(self);
We would need the same call for `Expr::Unary`, but I think the better solution is to fix it at https://github.com/kdy1/swc/blob/9f44d10bb2a28aa7d776c2a4243074e8f59494f7/crates/swc_ecma_transforms_compat/src/es2020/optional_chaining.rs#L207. That'll avoid a repeated iteration of `prop` and `args` (we do them during `gathering`). The only thing I missed was transforming the `base`

2023-07-03 18:05 UTC, jridgewell commented on crates/swc_ecma_transforms_compat/tests/optional-chaining/general-member-access/output.js
> -(0, (_c = (0, a?.b).c) === null || _c === void 0 ? void 0 : _c.d).e;
🤦

2023-07-04 05:05 UTC, jridgewell approved these changes, later dismissed

2023-07-04 06:59 UTC, merged