fix(es): Fix a bug
swc-project/swc pull request #7702
Opened 2023-07-25 03:32 UTC by kdy1

**Description:**

**Related issue:**

 - Closes #7700.

2023-07-25 03:48 UTC, kdy1 reviewed
swc-bump:
 - swc_ecma_usage_analyzer

2023-07-25 14:31 UTC, jridgewell requested changes

2023-07-28 15:28 UTC, jridgewell approved these changes

2023-07-28 16:56 UTC, kdy1 reviewed
reset ci

2023-07-28 16:57 UTC, merged