fix(es/minifier): Fix top-level check
swc-project/swc pull request #8583
Opened 2024-02-01 04:34 UTC by kdy1

**Description:**

Our logic for checking top-level was wrong.

2024-02-01 04:34 UTC, kdy1 reviewed
swc-bump:
 - swc_ecma_minifier

2024-02-01 21:36 UTC, Austaras requested changes
Everything else is good. If `module: true` and `toplevel: false`, we should still remove unused top level function.

2024-02-02 01:05 UTC, kdy1 commented
top_retain will be fixed by https://github.com/swc-project/swc/pull/8582

2024-02-02 01:09 UTC, Austaras submitted a review, later dismissed

2024-02-02 01:45 UTC, merged