fix(preset-env): Consider browserslist config if env.target not configured
swc-project/swc pull request #8921
Opened 2024-05-06 13:20 UTC by egfx-notifications

**Description:**

The `env.path` option in `.swcrc` was originally implemented for `browserslist`, but implementation was (unintentionally?) removed during the migration to `browserslist-rs` (#2845).
Searching the current directory for browserslist configuration was also dropped in the process.

This PR reimplements searching for browserslist configuration using the lookup functionality provided by `browserslist-rs`

**BREAKING CHANGE:**

This may be considered a breaking change since the previous (broken) behavior for unconfigured `env.targets` was to return a `BrowserData` struct with all `Option`s set to `None`. Now the result of a browserslist `defaults` query is returned instead. This probably was the original behavior with `browserslist`, though.

**Things to consider:**
- only works for non wasm targets as `browserslist-rs` does not provide configuration loading for wasm32 targets (which is probably to be expected that we won't check environment variables or search a filesystem in that case)
- `feat(preset-env): Let browserslist-rs handle default config path` changes the default for an unconfigured `env.path` from an empty string for wasm targets / current dir for other targets to a `None` value. `browserslist-rs` already looks up the current dir if `path` is `None` and it felt better to let it handle this case itself
  The commit which migrated from `browserslist` to `browserslist-rs` mentioned fixing the `default_path`, but does not mention what was broken and I also did not find any other usage of the `path` property. If the previous implementation was intentional, just ignore that last commit in the PR, the first two sufficiently address the bug.

**Related issue:**
Fixes  #3365
Implements #3085

2024-05-06 13:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/swc-project/swc?pullRequest=8921) <br/>All committers have signed the CLA.

2024-05-06 13:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/swc-project/swc?pullRequest=8921) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/swc-project/swc?pullRequest=8921) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/swc-project/swc?pullRequest=8921) it.</sub>

2024-05-06 14:19 UTC, egfx-notifications commented
It seems some of the tests fail due to them expecting a specific prerecorded results, but this result has now changed due to the previous default without a target being `BrowserData` with only `None` values and now it is `BrowserData` according to browserslist-rs `defaults` query, so some stuff that browser now understand natively is not transpiled.

Seems forcing a browserslist query when target is none is not the best approach. I won't try any fixes before hearing your feedback on how to handle this. Should we make the `env.path` option mandatory if a browserslist config lookup is desired?

2025-02-27 01:15 UTC, kdy1 commented on crates/preset_env_base/src/query.rs
> +            let distribs = browserslist::execute(&browserslist_opts)
Does this work with configs that execute javascript? cc @g-plane

2025-02-27 01:50 UTC, g-plane commented on crates/preset_env_base/src/query.rs
> +            let distribs = browserslist::execute(&browserslist_opts)
No, it doesn't execute any code.

2025-02-27 01:54 UTC, kdy1 reviewed
Can you rebase?

2025-02-27 10:19 UTC, jodaka commented
Nice to see some action here! Thanks @egfx-notifications

2025-02-27 16:01 UTC, egfx-notifications commented
I think I addressed all of the changes between my original commits and now. Unfortunately I can't run `cargo test` locally right now as my GLIBC version is too old. Let's see what CI says. I may set up a newer Ubuntu VM tomorrow if necessary.

2025-02-27 16:04 UTC, kdy1 commented
No worries, I‘ll update the tests if needed

2025-02-28 04:50 UTC, kdy1 requested changes

2025-02-28 04:50 UTC, kdy1 commented on .changeset/tidy-pots-report.md
> +preset_env_base: major
As this is a breaking change of swc_core, I'll merge it later.

2025-02-28 04:50 UTC, kdy1 commented on crates/preset_env_base/src/query.rs
> +                    .unwrap_or_else(|_| panic!("Invalid path \"{:?}\"", path))
I think we should not `panic!()` here. Can you return an instance of `anyhow::Error` instead?

2025-02-28 04:50 UTC, kdy1 commented on crates/preset_env_base/src/query.rs
> +                BrowserData::parse_versions(distribs).expect("failed to parse browser version");
Same here. We don't have to panic.

2025-03-03 05:19 UTC, kdy1 submitted a review, later dismissed
Thank you, and sorry for a (very) late review!

2025-03-24 05:37 UTC, kdy1 reviewed
I missed it while reviewing, but while trying to update tests to merge this PR, I found that this PR makes the `swc` crate ignore `jsc.target`.
Could you fix it?

2025-04-03 11:02 UTC, egfx-notifications commented
> I missed it while reviewing, but while trying to update tests to merge this PR, I found that this PR makes the `swc` crate ignore `jsc.target`. Could you fix it?

So, I looked into this and think I need a little more context. The only test failures I could find in the fixture tests were tests which explicitly **didn't** specify `jsc.target`. Those test cases have neither `env.target` nor `jsc.target` defined and as I mentioned the default if specifying no target is now the result of a browserslist `defaults` query, thus making this PR a breaking change. So those are test failures that were expected to happen until the fixtures are updated.
Note that the shopify tests 003-005 also fall into this "defaults" change since their `.swcrc` is wrong, they specify 
```json
{
    "jsc": {
        "parser": {
            "syntax": "ecmascript",
            "jsx": true
        }
    },
    "module": {
        "type": "commonjs"
    },
    "env": {
        "chrome": "50"
    }
}
```
when it should have been
```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": true
    }
  },
  "module": {
    "type": "commonjs"
  },
  "env": {
    "targets": {
      "chrome": "50"
    }
  }
}
```
So those fixtures weren't using that targeted chrome version from the start.

As far as I can tell `jsc.target` should still work as intended if specified.

2025-04-04 06:32 UTC, kdy1 commented
Oh, I think then it's fine and we should specify `jsc.target: es5` for those tests I think

2025-04-04 16:14 UTC, egfx-notifications commented
So, since `jsc.target` and `env` can't be used together and I think the `env` configurations in those test cases may be relevant for the case, I tried another route to solve this. I put `.browserslistrc` files without any content into the crate directories of the failing tests. This way it is picked up by autodiscovery if the test doesn't specify `jsc.target` or `env.targets`, but an empty query results in applying all possible transformations and thus emulates the previous default. This also means we don't have to regenerate all fixtures everytime `browserslist-rs` updates the result of the `defaults` query.  
Let me know if this is a suitable solution.

I also added a new test to check if `env.path` actually works.

2025-04-04 16:16 UTC, kdy1 commented
We don’t apply everything as default

2025-04-04 16:20 UTC, egfx-notifications commented
> We don’t apply everything as default

Ok, maybe this was phrased wrong. I mean that with the empty query in the autodiscovered files we take the same code path as previously without autodiscovery. So every transformation that was applied to the test cases before the PR without explicit configuration would also be applied now.

2025-04-07 03:08 UTC, kdy1 approved these changes
Thank you! I'll merge it once https://github.com/swc-project/swc/actions/runs/14299826346 is done!

2025-04-07 05:26 UTC, merged

2025-04-10 08:59 UTC, kdy1 reviewed
~I'll invert this PR with https://github.com/swc-project/swc/pull/10351~

Sorry it was already opt-in.