Fix 2022-03 decorators initialization order
swc-project/swc pull request #9760
Opened 2024-11-26 06:15 UTC by jzhan-canva

**Description:**
Fix the order of initialization for 2022-03 decorators.
TBH the [proposal](https://github.com/tc39/proposal-decorators) isn't very clear on how `init` is executed for [auto-accessor](https://github.com/tc39/proposal-decorators) decorator

**Related issue (if exists):**
#9669

2024-11-26 06:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/swc-project/swc?pullRequest=9760) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/swc-project/swc?pullRequest=9760) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/swc-project/swc?pullRequest=9760) it.</sub>

2024-11-26 06:16 UTC, jzhan-canva commented
@kdy1 please take a look on this draft

2024-11-26 06:49 UTC, kdy1 reviewed
Are you sure that this order change belongs to `2022-03` decorators?

I'm asking because the next version has initializer order reversed.

2024-11-26 06:55 UTC, jzhan-canva commented
the only thing I changed in this PR is to move `_init_proto` to before field initialization, I didn't change any logic of how `_init_proto` calls each initializer internally

I can double check the 2022-03 specification

2024-11-26 08:05 UTC, jzhan-canva commented
so I checked with babel playground with 2022-03 (assume it is the "correct" version)
between babel and my branch, there are two difference
1. how class is initialized by `addInitializer`: this is nothing to do with this pr, as this pr only change the class fields initialization 
2. how auto-accessor is initialized by `addInitializer` and `init`: babel use `addInitializer` first, my branch uses `init` first. this is controlled by the internal logic of `_init_proto`. and the proposal didn't specify which should run first

2024-11-27 04:50 UTC, kdy1 requested changes
Can you add some tests?

2024-11-27 06:36 UTC, jzhan-canva commented
> Can you add some tests?
will do

another question @kdy1, does swc have corporate CLA that my employer can sign?

2024-11-27 07:43 UTC, kdy1 commented
No, but I don’t think signing is necessary for this changes. I’m not going to monetize SWC or change license forever. I just want to be free while moving source codes in GitHub. I moved plugin codes from vercel/next.js to swc-project/plugins, and some npm packages within swc org, but that’s all.

2025-01-14 23:42 UTC, kdy1 requested changes

2025-01-14 23:42 UTC, kdy1 commented on crates/swc_ecma_transforms_proposal/src/decorator_impl.rs
> +        c.visit_mut_with(self);
This is wrong because of the time complexity. You should select the exact node before calling `visit_mut_with`

2025-01-15 06:53 UTC, jzhan-canva commented on crates/swc_ecma_transforms_proposal/src/decorator_impl.rs
> +        c.visit_mut_with(self);
sorry I don't get it, I don't see why moving this from line 721 to line 723 increases the time complexity

2025-01-15 06:56 UTC, kdy1 commented on crates/swc_ecma_transforms_proposal/src/decorator_impl.rs
> +        c.visit_mut_with(self);
Ah sorry, it's fine if it's about moving an existing line

2025-01-15 06:58 UTC, kdy1 approved these changes

2025-01-15 07:26 UTC, merged